project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left: 
      - text: "Hands-on Exercise"
        menu: 
         - text: "Hands-on Exercise 1"
           href: "Hands-On_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
         - text: "Hands-on Exercise 2"
           href: "Hands-On_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
         - text: "Hands-on Exercise 3"
           href: "Hands-On_Ex/Hand-on_Ex03/Hands-on_Ex03.html"
         - text: "Hands-on Exercise 4"
           href: "Hands-On_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
         - text: "Hands-on Exercise 5 - Global"
           href: "Hands-On_Ex/Hands-on_Ex05/Hands-on_Ex05-G lobal.html"
         - text: "Hands-on Exercise 5 - Local"
           href: "Hands-On_Ex/Hands-on_Ex05/Hands-On_Ex05-Local.html"
         - text: "Hands-on Exercise 6 - Geog segmentation"
           href: "Hands-On_Ex/Hands-on_Ex06/Hands-on_Ex6.html"
      - text: "In-class Exercise"
        menu: 
         - text: "In-class Exercise 2"
           href: "In-class_Ex/In-class-Ex02/In-class_Ex02.html"
         - text: "In-class Exercise 3"
           href: "In-class_Ex/In-class-Ex03/In-class-Ex03.html"
         - text: "In-class Exercise 5"
           href: "In-class_Ex/In-class-Ex05/In-class-Ex05.html"
         - text: "In-class Exercise 6"
           href: "In-class_Ex/In-class-Ex06/In-class_Ex06.html"
      - text: "Take home Exercise"
        menu: 
         - text: "Take home exercise 1"
           href: "Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.html"
         - text: "Take home exercise 2"
           href: "Take-Home_Ex/Take-Home_Ex02/Take-Home_Ex02.html"
         
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      
format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

