<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2024-03-24">

<title>IS415-GAA - Take-home Exercise 2: Application of Spatial and Spatio-temporal Analysis Methods to Discover the Distribution of Dengue Fever in Tainan City, Taiwan</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">IS415-GAA</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../Hands-On_Ex/Hands-on_Ex01/Hands-on_Ex01.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-On_Ex/Hands-on_Ex02/Hands-on_Ex02.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-On_Ex/Hand-on_Ex03/Hands-on_Ex03.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-On_Ex/Hands-on_Ex04/Hands-on_Ex04.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-On_Ex/Hands-on_Ex05/Hands-on_Ex05-Global.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 5 - Global</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-On_Ex/Hands-on_Ex05/Hands-On_Ex05-Local.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 5 - Local</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-On_Ex/Hands-on_Ex06/Hands-on_Ex6.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 6 - Geog segmentation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-On_Ex/Hands-on_Ex07/Hands-on_Ex7.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-On_Ex/Hands-on_Ex08/Hands-on_Ex08.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 8 - new</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-On_Ex/Hands-on_Ex09/Hands-on_Ex9.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 9</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">In-class Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercises">    
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class-Ex02/In-class_Ex02.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class-Ex03/In-class-Ex03.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class-Ex05/In-class-Ex05.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class-Ex06/In-class_Ex06.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 6</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Take home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.html" rel="" target="">
 <span class="dropdown-text">Take home exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-Home_Ex/Take-Home_Ex02/Take-Home_Ex02.html" rel="" target="">
 <span class="dropdown-text">Take home exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-Home_Ex/Take-Home_Ex03/Take-Home_Ex03.html" rel="" target="">
 <span class="dropdown-text">Take home exercise 3</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#background-context" id="toc-background-context" class="nav-link active" data-scroll-target="#background-context">1. Background &amp; Context</a>
  <ul class="collapse">
  <li><a href="#what-is-dengue" id="toc-what-is-dengue" class="nav-link" data-scroll-target="#what-is-dengue">1.1 What is Dengue?</a></li>
  <li><a href="#why-study-it" id="toc-why-study-it" class="nav-link" data-scroll-target="#why-study-it">1.2 Why Study It?</a></li>
  <li><a href="#what-in-particular-are-we-investigating" id="toc-what-in-particular-are-we-investigating" class="nav-link" data-scroll-target="#what-in-particular-are-we-investigating">1.3 What in particular are we investigating?</a></li>
  </ul></li>
  <li><a href="#packages" id="toc-packages" class="nav-link" data-scroll-target="#packages">2. Packages</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">3. Data</a>
  <ul class="collapse">
  <li><a href="#data-download-import" id="toc-data-download-import" class="nav-link" data-scroll-target="#data-download-import">3.1 Data Download &amp; Import</a></li>
  <li><a href="#geospatial-data" id="toc-geospatial-data" class="nav-link" data-scroll-target="#geospatial-data">3.2 Geospatial Data</a>
  <ul class="collapse">
  <li><a href="#import-the-data" id="toc-import-the-data" class="nav-link" data-scroll-target="#import-the-data">3.2.1 Import the data</a></li>
  <li><a href="#data-filtering" id="toc-data-filtering" class="nav-link" data-scroll-target="#data-filtering">3.2.2 Data Filtering</a></li>
  <li><a href="#assessing-geometric-validity" id="toc-assessing-geometric-validity" class="nav-link" data-scroll-target="#assessing-geometric-validity">3.2.3 Assessing Geometric Validity</a></li>
  <li><a href="#missing-values" id="toc-missing-values" class="nav-link" data-scroll-target="#missing-values">3.2.4 Missing values</a></li>
  <li><a href="#coordinate-reference-system" id="toc-coordinate-reference-system" class="nav-link" data-scroll-target="#coordinate-reference-system">3.2.5 Coordinate reference system</a></li>
  </ul></li>
  <li><a href="#aspatial-data" id="toc-aspatial-data" class="nav-link" data-scroll-target="#aspatial-data">3.3 Aspatial Data</a>
  <ul class="collapse">
  <li><a href="#import-the-data-1" id="toc-import-the-data-1" class="nav-link" data-scroll-target="#import-the-data-1">3.3.1 Import the data</a></li>
  <li><a href="#conversion-of-data-types" id="toc-conversion-of-data-types" class="nav-link" data-scroll-target="#conversion-of-data-types">3.3.2 Conversion of data types</a></li>
  <li><a href="#check-missing-data" id="toc-check-missing-data" class="nav-link" data-scroll-target="#check-missing-data">3.3.3 Check Missing Data</a></li>
  <li><a href="#conversion-of-latlong-into-geometry" id="toc-conversion-of-latlong-into-geometry" class="nav-link" data-scroll-target="#conversion-of-latlong-into-geometry">3.3.4 Conversion of Lat/Long into Geometry</a></li>
  <li><a href="#extracting-dengue-cases-from-relevant-weeks" id="toc-extracting-dengue-cases-from-relevant-weeks" class="nav-link" data-scroll-target="#extracting-dengue-cases-from-relevant-weeks">3.3.5 Extracting dengue cases from relevant weeks</a></li>
  <li><a href="#extracting-dengue-data-in-specific-areas" id="toc-extracting-dengue-data-in-specific-areas" class="nav-link" data-scroll-target="#extracting-dengue-data-in-specific-areas">3.3.6 Extracting dengue data in specific areas</a></li>
  <li><a href="#examining-dengue-incidents-town" id="toc-examining-dengue-incidents-town" class="nav-link" data-scroll-target="#examining-dengue-incidents-town">3.3.7 Examining dengue incidents /town</a></li>
  <li><a href="#examining-dengue-village" id="toc-examining-dengue-village" class="nav-link" data-scroll-target="#examining-dengue-village">3.3.8 Examining dengue /village</a></li>
  <li><a href="#examining-dengue-villageweek" id="toc-examining-dengue-villageweek" class="nav-link" data-scroll-target="#examining-dengue-villageweek">3.3.9 Examining dengue /village/week</a></li>
  <li><a href="#additional-data-wrangling" id="toc-additional-data-wrangling" class="nav-link" data-scroll-target="#additional-data-wrangling">3.8.9 Additional Data Wrangling</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#global-measures-of-spatial-association" id="toc-global-measures-of-spatial-association" class="nav-link" data-scroll-target="#global-measures-of-spatial-association">4. Global Measures of Spatial Association</a>
  <ul class="collapse">
  <li><a href="#calculating-contiguity-weights-queens-method" id="toc-calculating-contiguity-weights-queens-method" class="nav-link" data-scroll-target="#calculating-contiguity-weights-queens-method">4.1 Calculating Contiguity Weights: Queen’s method</a></li>
  <li><a href="#computing-global-moran-i" id="toc-computing-global-moran-i" class="nav-link" data-scroll-target="#computing-global-moran-i">4.2 <strong>Computing Global Moran’ I</strong></a></li>
  <li><a href="#performing-global-morans-i-test" id="toc-performing-global-morans-i-test" class="nav-link" data-scroll-target="#performing-global-morans-i-test">4.3 <strong>Performing Global Moran’s I test</strong></a></li>
  <li><a href="#performing-global-morans-permutation-test" id="toc-performing-global-morans-permutation-test" class="nav-link" data-scroll-target="#performing-global-morans-permutation-test">4.4 <strong>Performing Global Moran’s permutation test</strong></a></li>
  <li><a href="#computing-local-morans-i" id="toc-computing-local-morans-i" class="nav-link" data-scroll-target="#computing-local-morans-i">4.5 <strong>Computing local Moran’s I</strong></a>
  <ul class="collapse">
  <li><a href="#visualisng-local-morans-i" id="toc-visualisng-local-morans-i" class="nav-link" data-scroll-target="#visualisng-local-morans-i">4.5.1 <strong>Visualisng local Moran’s I</strong></a></li>
  <li><a href="#visualisng-p-value-of-local-morans-i" id="toc-visualisng-p-value-of-local-morans-i" class="nav-link" data-scroll-target="#visualisng-p-value-of-local-morans-i">4.5.1 <strong>Visualisng p value of local Moran’s I</strong></a></li>
  <li><a href="#visuaising-local-morans-i-and-p-value" id="toc-visuaising-local-morans-i-and-p-value" class="nav-link" data-scroll-target="#visuaising-local-morans-i-and-p-value">4.5.2 <strong>Visuaising local Moran’s I and p-value</strong></a></li>
  </ul></li>
  <li><a href="#visualising-lisa-map" id="toc-visualising-lisa-map" class="nav-link" data-scroll-target="#visualising-lisa-map">4.6 <strong>Visualising LISA map</strong></a></li>
  <li><a href="#hot-spot-and-cold-spot-area-analysis-hcsa" id="toc-hot-spot-and-cold-spot-area-analysis-hcsa" class="nav-link" data-scroll-target="#hot-spot-and-cold-spot-area-analysis-hcsa">4.7 <strong>Hot Spot and Cold Spot Area Analysis (HCSA)</strong></a>
  <ul class="collapse">
  <li><a href="#computing-local-gi-statistics" id="toc-computing-local-gi-statistics" class="nav-link" data-scroll-target="#computing-local-gi-statistics">4.7.1 Computing Local Gi* Statistics</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#creating-a-time-series-cube" id="toc-creating-a-time-series-cube" class="nav-link" data-scroll-target="#creating-a-time-series-cube">Creating a Time Series Cube</a>
  <ul class="collapse">
  <li><a href="#computing-gi" id="toc-computing-gi" class="nav-link" data-scroll-target="#computing-gi"><strong>Computing Gi*</strong></a>
  <ul class="collapse">
  <li><a href="#deriving-the-spatial-weights" id="toc-deriving-the-spatial-weights" class="nav-link" data-scroll-target="#deriving-the-spatial-weights"><strong>Deriving the spatial weights</strong></a></li>
  </ul></li>
  <li><a href="#computing-gi-1" id="toc-computing-gi-1" class="nav-link" data-scroll-target="#computing-gi-1"><strong>Computing Gi*</strong></a></li>
  </ul></li>
  <li><a href="#mann-kendall-test" id="toc-mann-kendall-test" class="nav-link" data-scroll-target="#mann-kendall-test"><strong>Mann-Kendall Test</strong></a>
  <ul class="collapse">
  <li><a href="#performing-emerging-hotspot-analysis" id="toc-performing-emerging-hotspot-analysis" class="nav-link" data-scroll-target="#performing-emerging-hotspot-analysis"><strong>Performing Emerging Hotspot Analysis</strong></a>
  <ul class="collapse">
  <li><a href="#visualising-the-distribution-of-ehsa-classes" id="toc-visualising-the-distribution-of-ehsa-classes" class="nav-link" data-scroll-target="#visualising-the-distribution-of-ehsa-classes"><strong>Visualising the distribution of EHSA classes</strong></a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-home Exercise 2: Application of Spatial and Spatio-temporal Analysis Methods to Discover the Distribution of Dengue Fever in Tainan City, Taiwan</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 24, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="background-context" class="level1">
<h1>1. Background &amp; Context</h1>
<p>In this take home exercise, our central subject of study would be Dengue.</p>
<section id="what-is-dengue" class="level2">
<h2 class="anchored" data-anchor-id="what-is-dengue">1.1 What is Dengue?</h2>
<p>Dengue is a disease spread by mosquitoes, particularly, the female Aedes aegypti and Aedes albopictus mosquitoes, in tropical and subtropical regions like Taiwan. It is transmitted to humans th</p>
<p>e-infected person, the mosquito is then infected. After approximately one week, the mosquito can then transmit&nbsp;the virus to other people they bite. It can result in sudden high fever, severe headache, joint pains and skin rashes.</p>
</section>
<section id="why-study-it" class="level2">
<h2 class="anchored" data-anchor-id="why-study-it">1.2 Why Study It?</h2>
<p>It can easily spread in areas in Taiwan due to the tropical climate, the high population density and numerous pools of stagnant water - which is a loved breeding ground for mosquitoes. It is imperative to track the speed at which it spreads and the areas in which it can spread in order to curtail its spread. And thats what we will be doing in this take home exercise.</p>
</section>
<section id="what-in-particular-are-we-investigating" class="level2">
<h2 class="anchored" data-anchor-id="what-in-particular-are-we-investigating">1.3 What in particular are we investigating?</h2>
<ol type="1">
<li>We firstly want to know if the outbreaks in Taiwan are independent of space and time. That means that the dengue instances would be randomly distributed and not show any pattern</li>
<li>If they are not independent of space and time, we would want to find certain areas that have high incidents of dengue (hotspots) and low incidents of it (coldspots). We also want to find if there are certain times of the year when outbreaks are more common.</li>
</ol>
</section>
</section>
<section id="packages" class="level1">
<h1>2. Packages</h1>
<p>In this section, I will be installing and loading R packages into our R environment to use them. I will also explain the utility of each package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, tidyverse, tmap, sfdep,zoo, Kendall)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><em>Sf</em></p>
<p>It provides a comprehensive and standardized way to represent and manipulate spatial data.</p>
<ol type="1">
<li>Allows you to represent points, lines and polygons</li>
<li>Allows you to represent data using coordinate reference system, and transform data using that.</li>
</ol>
<p><strong><em>tidyverse</em></strong>&nbsp;</p>
<p>Imagine you have a bunch of dirty data that you woul have to handle. The Tidyverse package helps you handle the data. It has a bunch of packages within it to help handle data. It can do the following:</p>
<ol type="1">
<li><p>readr - reading and writing data into or out of a spreadsheet</p></li>
<li><p>tidyr - organizing and tidying up your data</p></li>
<li><p>ggplot2 - visualizing your data</p></li>
<li><p>dpylr - mainpulating your data, like doing some basic math to it.</p></li>
</ol>
<p><strong><em>tmap</em></strong></p>
<p>Shows distribution of a characteristic across a geographic space.</p>
<p>sfdep</p>
</section>
<section id="data" class="level1">
<h1>3. Data</h1>
<section id="data-download-import" class="level2">
<h2 class="anchored" data-anchor-id="data-download-import">3.1 Data Download &amp; Import</h2>
<p>Let us first look at the data we are utilising to conduct this analysis.</p>
<table class="table">
<caption>Overview Off Data Used</caption>
<colgroup>
<col style="width: 39%">
<col style="width: 45%">
<col style="width: 6%">
<col style="width: 8%">
</colgroup>
<tbody>
<tr class="odd">
<td>Data Name</td>
<td>Description</td>
<td>Type</td>
<td>Format</td>
</tr>
<tr class="even">
<td>Dengue Daily</td>
<td>This data denotes the locations and time of each dengue incident in Taiwan.</td>
<td>Geospatial</td>
<td>CSV</td>
</tr>
<tr class="odd">
<td>Historical map data of the village boundary (TWD97 longitude and latitude)</td>
<td>This data provides the internal and external boundary of Taiwan at the village level.</td>
<td>Geospatial</td>
<td>ESRI shapefile</td>
</tr>
</tbody>
</table>
</section>
<section id="geospatial-data" class="level2">
<h2 class="anchored" data-anchor-id="geospatial-data">3.2 Geospatial Data</h2>
<p>In this section, we will be importing and wrangling our data. We do this because data might not always be in the format that is suitable for our analysis, and hence, conversion to a suitable format is imperative.</p>
<section id="import-the-data" class="level3">
<h3 class="anchored" data-anchor-id="import-the-data">3.2.1 Import the data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>taiwan <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/geospatial"</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">layer =</span> <span class="st">"TAINAN_VILLAGE"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `TAINAN_VILLAGE' from data source 
  `C:\shaysnutss\IS1455-GAA\Take-Home_Ex\Take-Home_Ex02\data\geospatial' 
  using driver `ESRI Shapefile'
Simple feature collection with 649 features and 10 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 120.0269 ymin: 22.88751 xmax: 120.6563 ymax: 23.41374
Geodetic CRS:  TWD97</code></pre>
</div>
</div>
<p>Let’s look at the data to understand it better.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(taiwan)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 10 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 120.053 ymin: 22.93251 xmax: 120.2905 ymax: 23.16919
Geodetic CRS:  TWD97
     VILLCODE COUNTYNAME TOWNNAME VILLNAME        VILLENG COUNTYID COUNTYCODE
1 67000280002     臺南市   歸仁區   六甲里    Liujia Vil.        D      67000
2 67000350032     臺南市   安南區   青草里   Qingcao Vil.        D      67000
3 67000150009     臺南市   七股區   溪南里     Xinan Vil.        D      67000
4 67000150010     臺南市   七股區   七股里      Qigu Vil.        D      67000
5 67000150008     臺南市   七股區   龍山里  Longshan Vil.        D      67000
6 67000150017     臺南市   七股區   中寮里 Zhongliao Vil.        D      67000
  TOWNID TOWNCODE NOTE                       geometry
1    D33 67000280 &lt;NA&gt; POLYGON ((120.2725 22.95868...
2    D06 67000350 &lt;NA&gt; POLYGON ((120.1176 23.08387...
3    D22 67000150 &lt;NA&gt; POLYGON ((120.121 23.1355, ...
4    D22 67000150 &lt;NA&gt; POLYGON ((120.1312 23.1371,...
5    D22 67000150 &lt;NA&gt; POLYGON ((120.0845 23.13503...
6    D22 67000150 &lt;NA&gt; POLYGON ((120.126 23.16917,...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(taiwan)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "sf"         "data.frame"</code></pre>
</div>
</div>
<p>We can see that the data is in a data frame of type sf. This data frame talks about <u>each village in Tainan city (in Taiwan)</u>, and accompanying information like which county and town the village is in.</p>
<p>Let’s see how Tainan city in Taiwan looks like when it is divided by its villages. In this plot below, we see Taiwan divided by villages, and each color represents a different town that it is part of.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qtm</span>(taiwan, <span class="at">fill=</span><span class="st">"TOWNID"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex02_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>However, we only need towns D01, D02, D04, D06, D07, D08, D32 and D39.</p>
</section>
<section id="data-filtering" class="level3">
<h3 class="anchored" data-anchor-id="data-filtering">3.2.2 Data Filtering</h3>
<p>Let’s now filter the rows in our Taiwan data frame to contain rows/villages from just these particular towns: D01, D02, D04, D06, D07, D08, D32 and D39.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>taiwan_filtered <span class="ot">&lt;-</span> taiwan <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(TOWNID <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">'D01'</span>, <span class="st">'D02'</span>, <span class="st">'D04'</span>, <span class="st">'D06'</span>, <span class="st">'D07'</span>, <span class="st">'D08'</span>, <span class="st">'D32'</span>, <span class="st">'D39'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s visualise the data again.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qtm</span>(taiwan_filtered, <span class="at">fill=</span><span class="st">"TOWNID"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex02_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here we see that we were successful in our filtering, we have got the villages just in the towns that we are interested in. This is a much smaller subset of the data we were working with, hopefully processing speeds would be higher too!</p>
</section>
<section id="assessing-geometric-validity" class="level3">
<h3 class="anchored" data-anchor-id="assessing-geometric-validity">3.2.3 Assessing Geometric Validity</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">which</span>(<span class="fu">st_is_valid</span>(taiwan_filtered) <span class="sc">==</span> <span class="cn">FALSE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>0 means that none of our rows have invalid geometries and that we could move on peacefully.</p>
</section>
<section id="missing-values" class="level3">
<h3 class="anchored" data-anchor-id="missing-values">3.2.4 Missing values</h3>
<p>We want to check if there are any empty rows. Datasets can be huge and consequently, we could have many empty rows that is just a waste of memory and processing power. Removing them would be useful.</p>
<p>Here’s how we do it:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the filter function to check for empty rows</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>empty_rows <span class="ot">&lt;-</span> taiwan_filtered <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter_all</span>(<span class="fu">all_vars</span>(<span class="fu">is.na</span>(.)))</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Check if there are any empty rows</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">nrow</span>(empty_rows) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"There are empty rows in the sf data tibble.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"There are no empty rows in the sf data tibble.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>There are no empty rows in the sf data tibble.</code></pre>
</div>
</div>
<p>Luckily, we have no empty rows either!</p>
</section>
<section id="coordinate-reference-system" class="level3">
<h3 class="anchored" data-anchor-id="coordinate-reference-system">3.2.5 Coordinate reference system</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(taiwan_filtered)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: TWD97 
  wkt:
GEOGCRS["TWD97",
    DATUM["Taiwan Datum 1997",
        ELLIPSOID["GRS 1980",6378137,298.257222101,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    USAGE[
        SCOPE["Horizontal component of 3D system."],
        AREA["Taiwan, Republic of China - onshore and offshore - Taiwan Island, Penghu (Pescadores) Islands."],
        BBOX[17.36,114.32,26.96,123.61]],
    ID["EPSG",3824]]</code></pre>
</div>
</div>
</section>
</section>
<section id="aspatial-data" class="level2">
<h2 class="anchored" data-anchor-id="aspatial-data">3.3 Aspatial Data</h2>
<section id="import-the-data-1" class="level3">
<h3 class="anchored" data-anchor-id="import-the-data-1">3.3.1 Import the data</h3>
<p>Let’s import the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>dengue <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/aspatial/Dengue_Daily.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s explore how the data is like!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dengue)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      發病日 個案研判日     通報日 性別 年齡層 居住縣市 居住鄉鎮 居住村里
1 1998/01/02       None 1998/01/07   男  40-44   屏東縣   屏東市     None
2 1998/01/03       None 1998/01/14   男  30-34   屏東縣   東港鎮     None
3 1998/01/13       None 1998/02/18   男  55-59   宜蘭縣   宜蘭市     None
4 1998/01/15       None 1998/01/23   男  35-39   高雄市   苓雅區     None
5 1998/01/20       None 1998/02/04   男  55-59   宜蘭縣   五結鄉     None
6 1998/01/22       None 1998/02/19   男  20-24   桃園市   蘆竹區     None
     最小統計區 最小統計區中心點X 最小統計區中心點Y   一級統計區 二級統計區
1 A1320-0136-00     120.505898941      22.464206650 A1320-04-008   A1320-04
2 A1303-0150-00     120.453657460      22.466338948 A1303-09-007   A1303-09
3 A0201-0449-00     121.751433765      24.749214667 A0201-23-006   A0201-23
4 A6408-0153-00     120.338158907      22.630316700 A6408-10-010   A6408-10
5 A0209-0232-00     121.798235373      24.684507639 A0209-10-005   A0209-10
6          None              None              None         None       None
  感染縣市 感染鄉鎮 感染村里 是否境外移入 感染國家 確定病例數 居住村里代碼
1     None     None     None           否     None          1         None
2     None     None     None           是     None          1         None
3     None     None     None           是     None          1         None
4     None     None     None           否     None          1         None
5     None     None     None           否     None          1         None
6     None     None     None           是     None          1         None
  感染村里代碼 血清型 內政部居住縣市代碼 內政部居住鄉鎮代碼 內政部感染縣市代碼
1         None   None              10013            1001301               None
2         None 第二型              10013            1001303               None
3         None   None              10002            1000201               None
4         None   None                 64            6400800               None
5         None   None              10002            1000209               None
6         None   None                 68            6800500               None
  內政部感染鄉鎮代碼
1               None
2               None
3               None
4               None
5               None
6               None</code></pre>
</div>
</div>
<p>We realise that the columns are in Chinese, so let’s translate them to english so that we can understand them better. I have used Google translate to individually translate each column to english</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>new_names <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Onset_date"</span>, <span class="st">"judgement_date"</span>, <span class="st">"notification_date"</span>, <span class="st">"gender"</span>, <span class="st">"age_group"</span>, <span class="st">"country_city_residence"</span>, <span class="st">"residential_township"</span>, <span class="st">"residential_village"</span>, <span class="st">"min_stat_area"</span>, <span class="st">"min_stat_area_center_point_x"</span>, <span class="st">"min_stat_area_center_point_y"</span>, <span class="st">"first_level_stat_area"</span>, <span class="st">"second_level_stat_area"</span>, <span class="st">"infected_counties_cities"</span>, <span class="st">"infected_towns"</span>, <span class="st">"infected_villages"</span>,</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>               <span class="st">"immigrant"</span>, <span class="st">"country_of_infection"</span>, <span class="st">"confirmed_cases_number"</span>, <span class="st">"village_residence_code"</span>, <span class="st">"infected_village_code"</span>, <span class="st">"serotype"</span>, <span class="st">"interior_county_city_ministry_code"</span>, <span class="st">"interior_residence_township_ministry_code"</span>, <span class="st">"interior_infection_county_ministry_code"</span>, </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>               <span class="st">"interior_infection_township_ministry_code"</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>               )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(dengue) <span class="ot">&lt;-</span> new_names</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s check if the translation has worked!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(dengue)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Onset_date"                               
 [2] "judgement_date"                           
 [3] "notification_date"                        
 [4] "gender"                                   
 [5] "age_group"                                
 [6] "country_city_residence"                   
 [7] "residential_township"                     
 [8] "residential_village"                      
 [9] "min_stat_area"                            
[10] "min_stat_area_center_point_x"             
[11] "min_stat_area_center_point_y"             
[12] "first_level_stat_area"                    
[13] "second_level_stat_area"                   
[14] "infected_counties_cities"                 
[15] "infected_towns"                           
[16] "infected_villages"                        
[17] "immigrant"                                
[18] "country_of_infection"                     
[19] "confirmed_cases_number"                   
[20] "village_residence_code"                   
[21] "infected_village_code"                    
[22] "serotype"                                 
[23] "interior_county_city_ministry_code"       
[24] "interior_residence_township_ministry_code"
[25] "interior_infection_county_ministry_code"  
[26] "interior_infection_township_ministry_code"</code></pre>
</div>
</div>
</section>
<section id="conversion-of-data-types" class="level3">
<h3 class="anchored" data-anchor-id="conversion-of-data-types">3.3.2 Conversion of data types</h3>
<p>The data type of all the fields in the data table is char, which doesn’t make sense for numeric values such as the x&amp;y coordinates and the onset date.</p>
<p>Let’s change the data type of onset date.</p>
<p>In this code snippet, we convert onset date to a date datatype (it was char before). Then we create a new week column to detect the week of the onset date (we need it later to extract relevant weeks)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>dengue_new <span class="ot">&lt;-</span> dengue</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>dengue_new<span class="sc">$</span>Onset_date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(dengue_new<span class="sc">$</span>Onset_date)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>dengue_new<span class="sc">$</span>week <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">format</span>(dengue_new<span class="sc">$</span>Onset_date, <span class="st">"%V"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s convert data type of X and Y coordinates.</p>
<p>However, I have noticed that some x and y coordinates are non numerical like “none” , and these will not be able to be converted. lets remove them first.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>dengue_new <span class="ot">&lt;-</span> dengue_new <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">grepl</span>(<span class="st">"^[+-]?[0-9]*[.]?[0-9]+$"</span>, min_stat_area_center_point_x))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>dengue_new <span class="ot">&lt;-</span> dengue_new <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">grepl</span>(<span class="st">"^[+-]?[0-9]*[.]?[0-9]+$"</span>, min_stat_area_center_point_y))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now let’s do the conversion.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>dengue_new<span class="sc">$</span>min_stat_area_center_point_x <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(dengue_new<span class="sc">$</span>min_stat_area_center_point_x)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>dengue_new<span class="sc">$</span>min_stat_area_center_point_y <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(dengue_new<span class="sc">$</span>min_stat_area_center_point_y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="check-missing-data" class="level3">
<h3 class="anchored" data-anchor-id="check-missing-data">3.3.3 Check Missing Data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>dengue[<span class="fu">rowSums</span>(<span class="fu">is.na</span>(dengue))<span class="sc">!=</span><span class="dv">0</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] Onset_date                               
 [2] judgement_date                           
 [3] notification_date                        
 [4] gender                                   
 [5] age_group                                
 [6] country_city_residence                   
 [7] residential_township                     
 [8] residential_village                      
 [9] min_stat_area                            
[10] min_stat_area_center_point_x             
[11] min_stat_area_center_point_y             
[12] first_level_stat_area                    
[13] second_level_stat_area                   
[14] infected_counties_cities                 
[15] infected_towns                           
[16] infected_villages                        
[17] immigrant                                
[18] country_of_infection                     
[19] confirmed_cases_number                   
[20] village_residence_code                   
[21] infected_village_code                    
[22] serotype                                 
[23] interior_county_city_ministry_code       
[24] interior_residence_township_ministry_code
[25] interior_infection_county_ministry_code  
[26] interior_infection_township_ministry_code
&lt;0 rows&gt; (or 0-length row.names)</code></pre>
</div>
</div>
<p>Thankfully we have no missing data! Let’s proceed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>dengue_before_geo <span class="ot">&lt;-</span> dengue_new</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="conversion-of-latlong-into-geometry" class="level3">
<h3 class="anchored" data-anchor-id="conversion-of-latlong-into-geometry">3.3.4 Conversion of Lat/Long into Geometry</h3>
<p>We want to convert the lat long to a point so that we could conduct spatial point analysis!</p>
<p>Now, let’s do the conversion!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>dengue_new <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(dengue_new, <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"min_stat_area_center_point_x"</span>, <span class="st">"min_stat_area_center_point_y"</span>), <span class="at">crs =</span> <span class="dv">3824</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s look at our <code>dengue_new</code> now. it’s indeed projected in TWD97 and that’s what we wanted!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_geometry</span>(dengue_new)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Geometry set for 106081 features 
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 118.3081 ymin: 21.92574 xmax: 121.9826 ymax: 26.15617
Geodetic CRS:  TWD97
First 5 geometries:</code></pre>
</div>
</div>
</section>
<section id="extracting-dengue-cases-from-relevant-weeks" class="level3">
<h3 class="anchored" data-anchor-id="extracting-dengue-cases-from-relevant-weeks">3.3.5 Extracting dengue cases from relevant weeks</h3>
<p>We are asked to extract dengue cases from only week 31 to week 50 of 2023. We do not need data from other time periods. So, let’s do that!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>dengue_new <span class="ot">&lt;-</span> dengue_new <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">year</span>(Onset_date) <span class="sc">==</span> <span class="dv">2023</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="sc">&amp;</span> (week <span class="sc">&gt;=</span><span class="dv">31</span> <span class="sc">&amp;</span> week <span class="sc">&lt;=</span> <span class="dv">50</span>))</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>dengue_before_geo <span class="ot">&lt;-</span> dengue_before_geo <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">year</span>(Onset_date) <span class="sc">==</span> <span class="dv">2023</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="sc">&amp;</span> (week <span class="sc">&gt;=</span><span class="dv">31</span> <span class="sc">&amp;</span> week <span class="sc">&lt;=</span> <span class="dv">50</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="extracting-dengue-data-in-specific-areas" class="level3">
<h3 class="anchored" data-anchor-id="extracting-dengue-data-in-specific-areas">3.3.6 Extracting dengue data in specific areas</h3>
<p>Our geospatial data, <code>taiwan_filtered,</code> provides the boundaries of villages in Tainan City in particular - not the whole of taiwan. And we had <code>taiwan_``filtered</code> created after selecting only a few towns in Tainan City. We need to make sure that the <code>dengue_new</code> data only corresponds to the areas defined in the <code>taiwan_``filtered</code> area.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co">#dengue_tainan &lt;- st_intersection(taiwan_filtered, dengue_new)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s write this to rds as it was a time consuming task and we do not want to execute this agaain.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co">#write_rds(dengue_tainan, "../../data/rds/dengue_tainan.rds")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>dengue_tainan <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"../../data/rds/dengue_tainan.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(taiwan_filtered) <span class="sc">+</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"TOWNID"</span>) <span class="sc">+</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(dengue_tainan) <span class="sc">+</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex02_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="examining-dengue-incidents-town" class="level3">
<h3 class="anchored" data-anchor-id="examining-dengue-incidents-town">3.3.7 Examining dengue incidents /town</h3>
<p>By looking at our graphical analysis, we can tell that villages in Towns. D01, D08, D04 have a high density of dengue cases.</p>
<p>Let’s see if that is right by plotting the number of dengue incidents per TOWNID!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>dengue_summary <span class="ot">&lt;-</span> dengue_tainan <span class="sc">%&gt;%</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(TOWNID) <span class="sc">%&gt;%</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">incidents =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">'drop'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s plot the results!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dengue_summary, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(TOWNID, <span class="sc">-</span>incidents), <span class="at">y =</span> incidents)) <span class="sc">+</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Town ID"</span>, <span class="at">y =</span> <span class="st">"Number of Incidents"</span>, <span class="at">title =</span> <span class="st">"Dengue Incidents by Town"</span>) <span class="sc">+</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">65</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex02_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Guess we weren’t fully correct! The towns with the more incidents were D01, D06 and D39. But it is important to note that the top 5 towns have very similar number of incidents</p>
</section>
<section id="examining-dengue-village" class="level3">
<h3 class="anchored" data-anchor-id="examining-dengue-village">3.3.8 Examining dengue /village</h3>
<p>Now, let’s examine the number of incidents per village. And since we already examined the number of incidents per town, let’s <strong>see if the villages with the highest number of incidents come from towns with the highest number of incidents!</strong></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>This is very important to do so, so that we can make links between different facets of data - villages and towns and gain a better understanding of the geospatial distribution of the incidents.</p>
</div>
</div>
<p>In this section, not only are we aiming to find the villages with the highest number of incidents, we are trying to link them to the town they are from.</p>
<p>As our first task, let’s map the villages to their town on our own.</p>
<section id="mapping-town-to-village" class="level4">
<h4 class="anchored" data-anchor-id="mapping-town-to-village">3.3.8.1 Mapping town to village</h4>
<p>In our dengue_tainan data frame, each row corresponds to a particular incident of dengue in a particular point. There might be multiple points referring to the same village.</p>
<p>We need to remove the geometry column for this so that we can remove the uniqueness for each row and can group all the same village ids together. To do so, we change the data type of dengue_tainan and store it in dengue_tainan_no_geom.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>dengue_tainan_no_geom <span class="ot">&lt;-</span> <span class="fu">st_set_geometry</span>(dengue_tainan, <span class="cn">NULL</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now let’s do the mapping between villagecode and townid.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>villcode_townid_mapping <span class="ot">&lt;-</span> dengue_tainan_no_geom <span class="sc">%&gt;%</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(VILLCODE, TOWNID) <span class="sc">%&gt;%</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>()</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(villcode_townid_mapping)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       VILLCODE TOWNID
212 67000310004    D39
27  67000320003    D01
19  67000310001    D39
128 67000270012    D32
246 67000310025    D39
150 67000310037    D39</code></pre>
</div>
</div>
<p>We have done it!</p>
</section>
<section id="calculating-top-10-villages" class="level4">
<h4 class="anchored" data-anchor-id="calculating-top-10-villages">3.3.8.1 Calculating top 10 villages</h4>
<p>Here we group by villcode so that we can get the number of incidents per village</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>dengue_summary <span class="ot">&lt;-</span> dengue_tainan <span class="sc">%&gt;%</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(VILLCODE) <span class="sc">%&gt;%</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">incidents =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">'drop'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s remove the geometry column here as well so that we can join it with the mapping we made above. We do this because we use left_join for combining the mapping with the number of incidents per village, and it does not allow us to have a geometry column</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>dengue_summary  <span class="ot">&lt;-</span> <span class="fu">st_set_geometry</span>(dengue_summary , <span class="cn">NULL</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now let’s do the join.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>dengue_summary <span class="ot">&lt;-</span> dengue_summary <span class="sc">%&gt;%</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(villcode_townid_mapping, <span class="at">by =</span> <span class="st">"VILLCODE"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s now get the top 10 villages with the most number of incidents</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>top_10_villages <span class="ot">&lt;-</span> dengue_summary <span class="sc">%&gt;%</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(incidents)) <span class="sc">%&gt;%</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(<span class="at">order_by =</span> incidents, <span class="at">n =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here, let’s plot the number of incidents for the top 10 villages with the most incidents, in an ascending order. Each village will be uniquely colored based on the town it is from, so that we can make connections between the towns and villages with the most incidents.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(top_10_villages, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(VILLCODE, <span class="sc">-</span>incidents), <span class="at">y =</span> incidents, <span class="at">fill =</span> <span class="fu">as.factor</span>(TOWNID))) <span class="sc">+</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>() <span class="sc">+</span> </span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Top 10 Villages with Most Dengue Incidents"</span>,</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Village Code"</span>,</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Number of Incidents"</span>,</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Town ID"</span>) <span class="sc">+</span></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>), <span class="co"># Improve x-axis label readability</span></span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position =</span> <span class="st">"bottom"</span>) <span class="co"># Adjust legend position</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex02_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>To analyse the graph above, let’s refer to our previous chart depicting the towns with the most incidents.</p>
<p><img src="images/clipboard-77413975.png" class="img-fluid"></p>
<p>From the first graph, we can see that the village with the most incidents is from D39, however, D39 isactually the town with the 3rd most number of incidents.</p>
<p>But if D39 is a town with the 3rd most number of incidents, it is actually corroborated by the fact that in the first graph, 3 of the top 10 villages with the most incidents come from D39</p>
<p>From the second graph, we can see that D06 is the town with the second most number of incidents, 4 of the top 10 villages with most incidents actually come from town D06, thus making the second graph make a lot of sense!</p>
<p>What the interesting or controversial thing is, is that, D01 is said to be the town with the most number of incidents, but only one village from town D01 made it to the top 10 list! HMmm.. That means that multiple villages in D01 had a smaller number of incidents, whilst D36 maybe just had a select few villages with high number of cases.</p>
</section>
</section>
<section id="examining-dengue-villageweek" class="level3">
<h3 class="anchored" data-anchor-id="examining-dengue-villageweek">3.3.9 Examining dengue /village/week</h3>
<p>Let’s get all the weeks for each village code. We have to use village code as the unique identifier as there are 258 unique village codes but 253 unique village names. That means, there are multiple village codes with the same village =eng, so it’s important to disregard villageeng.</p>
<p>So let’s get all the weeks from 30-50 for each village code.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>villagecode_week_set <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">VILLCODE =</span> <span class="fu">unique</span>(taiwan_filtered<span class="sc">$</span>VILLCODE), <span class="at">week=</span> <span class="fu">seq</span>(<span class="dv">31</span>,<span class="dv">50</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Let us now see how many dengue incidents are there per week per village!</strong></p>
<p>Let’s group by the week and the village code, and then add it up to calculate the total number of incidents</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>dengue_summary <span class="ot">&lt;-</span> dengue_tainan <span class="sc">%&gt;%</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(VILLCODE, week) <span class="sc">%&gt;%</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">incidents =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">'drop'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>dengue_pervillage_week <span class="ot">&lt;-</span> dengue_summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dengue_summary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 3 fields
Geometry type: GEOMETRY
Dimension:     XY
Bounding box:  xmin: 120.2534 ymin: 22.98918 xmax: 120.2721 ymax: 22.994
Geodetic CRS:  TWD97
# A tibble: 6 × 4
  VILLCODE     week incidents                                           geometry
  &lt;chr&gt;       &lt;dbl&gt;     &lt;int&gt;                                     &lt;GEOMETRY [°]&gt;
1 67000270001    33         1                          POINT (120.2583 22.99218)
2 67000270001    34         1                          POINT (120.2612 22.99222)
3 67000270001    35         2 MULTIPOINT ((120.2625 22.994), (120.2668 22.98918…
4 67000270001    36         3 MULTIPOINT ((120.2555 22.99274), (120.2574 22.989…
5 67000270001    37         5 MULTIPOINT ((120.2555 22.99274), (120.2591 22.992…
6 67000270001    38         4 MULTIPOINT ((120.2534 22.99117), (120.2639 22.991…</code></pre>
</div>
</div>
<p>There are many rows in this data table, so let’s find out the particular weeks in specific villages that had the highest number of incidents.</p>
<p>In this code snippet, we get sort the incident values in a descending order, then take the top 10 rows, and change the columns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>top_10_incidents <span class="ot">&lt;-</span> dengue_summary <span class="sc">%&gt;%</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(incidents)) <span class="sc">%&gt;%</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(<span class="at">order_by =</span> incidents, <span class="at">n =</span> <span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">concatenated_vill_week =</span> <span class="fu">paste</span>(<span class="st">"vill"</span>, VILLCODE, <span class="st">"at week"</span>, week))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s plot it to see which weeks and villages had the most incidents</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(top_10_incidents, <span class="fu">aes</span>(<span class="at">x =</span> concatenated_vill_week, <span class="at">y =</span> incidents, <span class="at">fill =</span> VILLCODE)) <span class="sc">+</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Village Code and Week"</span>, <span class="at">y =</span> <span class="st">"Number of Incidents"</span>, <span class="at">title =</span> <span class="st">"Top 10 Dengue Incidents by Village and Week"</span>) <span class="sc">+</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">vjust =</span> <span class="dv">1</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex02_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can see that <code>dengue_summary</code> does not have all the weeks for each unique <code>VILLCODE</code> . So we must ensure that the resulting data table has a row represnting each week for each village code.</p>
<p>So we left join with the data frame with all the week-villagecode combinations so that all the ocmbinations will be included. The last line of code replaces week-villagecode combinations with no incidents as 0.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>final_set<span class="ot">&lt;-</span> <span class="fu">left_join</span>(villagecode_week_set, dengue_summary, <span class="at">by=</span> <span class="fu">c</span>(<span class="st">"VILLCODE"</span>, <span class="st">"week"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">replace</span>(<span class="fu">is.na</span>(.), <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>final_set <span class="ot">&lt;-</span> <span class="fu">left_join</span>(taiwan_filtered, final_set, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"VILLCODE"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s drop geometry.y as it refers to the dengue incident point, and we don’t need that as we are looking at number of incidents per village per week</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>final_set<span class="ot">&lt;-</span> final_set <span class="sc">%&gt;%</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>geometry.y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="additional-data-wrangling" class="level3">
<h3 class="anchored" data-anchor-id="additional-data-wrangling">3.8.9 Additional Data Wrangling</h3>
<p>Let’s get the number of incidents per village</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>dengue_per_village <span class="ot">&lt;-</span> dengue_tainan <span class="sc">%&gt;%</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(VILLCODE) <span class="sc">%&gt;%</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">incidents =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">'drop'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As I am trying to investigate the number of incidents per week, i do not need the gemoetries of each individual point that have amalgamated into a multipoint. So, let’s remove geome</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>dengue_per_village  <span class="ot">&lt;-</span> <span class="fu">st_set_geometry</span>(dengue_per_village , <span class="cn">NULL</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s perform left join.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>tryNow <span class="ot">&lt;-</span> <span class="fu">left_join</span>(taiwan_filtered, dengue_per_village, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"VILLCODE"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(tryNow) <span class="sc">+</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">"incidents"</span>,</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">style =</span> <span class="st">"quantile"</span>,</span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">palette =</span> <span class="st">"Purples"</span>,</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">title =</span> <span class="st">"Number of Dengue Cases"</span>) <span class="sc">+</span></span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Number of Dengue Cases"</span>,</span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="dv">1</span>,</span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.height =</span> <span class="fl">0.4</span>,</span>
<span id="cb62-11"><a href="#cb62-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">legend.width =</span> <span class="fl">0.3</span>,</span>
<span id="cb62-12"><a href="#cb62-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb62-13"><a href="#cb62-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb62-14"><a href="#cb62-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex02_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
</section>
<section id="global-measures-of-spatial-association" class="level1">
<h1>4. Global Measures of Spatial Association</h1>
<p>In statstics, we are interested to find out if the observed distribution follows normal distribution. we need to go beyond EDA and actually confirm that the distribution follows normal distribution.</p>
<p>To confirm normal distribution, we need to conduct a formal statistical test.</p>
<p>Before we can conduct statistical test, we need to understand how spatial relationships between geographical areas can be defined mathematically. And this is known as spatial weights</p>
<section id="calculating-contiguity-weights-queens-method" class="level2">
<h2 class="anchored" data-anchor-id="calculating-contiguity-weights-queens-method">4.1 Calculating Contiguity Weights: Queen’s method</h2>
<p>Here we are trying to determine the neighbours of each village, and then we are determining how much each neighbour could affect the focus location (through weights)</p>
<p>When doing it, i got an error that there were NA values. When we looked at our tryNow data frame, there was a column called Note with only NA values.</p>
<p>Hence, let’s remove that.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>tryNow <span class="ot">&lt;-</span> tryNow <span class="sc">%&gt;%</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>NOTE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>tryNow <span class="ot">&lt;-</span> tidyr<span class="sc">::</span><span class="fu">drop_na</span>(tryNow)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, let’s calculate the weights of neighbouring villages of each focal village.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>wm_q <span class="ot">&lt;-</span> tryNow <span class="sc">%&gt;%</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">nb =</span> <span class="fu">st_contiguity</span>(geometry),</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">wt =</span> <span class="fu">st_weights</span>(nb,</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">style =</span> <span class="st">"W"</span>),</span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">.before =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>wm_q</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 257 features and 12 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 120.0627 ymin: 22.89401 xmax: 120.2925 ymax: 23.09144
Geodetic CRS:  TWD97
First 10 features:
                                             nb
1                                   6, 118, 160
2                       126, 128, 138, 167, 221
3          68, 69, 171, 180, 183, 184, 187, 199
4                    94, 97, 100, 104, 181, 206
5                              12, 13, 248, 254
6                      1, 12, 13, 118, 160, 248
7                               54, 98, 99, 200
8  9, 73, 75, 115, 125, 144, 156, 157, 165, 185
9                         8, 110, 115, 125, 165
10                  11, 159, 161, 165, 235, 257
                                                                 wt    VILLCODE
1                                   0.3333333, 0.3333333, 0.3333333 67000350032
2                                           0.2, 0.2, 0.2, 0.2, 0.2 67000270011
3            0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125 67000370005
4  0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667 67000330004
5                                            0.25, 0.25, 0.25, 0.25 67000350028
6  0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667 67000350030
7                                            0.25, 0.25, 0.25, 0.25 67000370009
8                  0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1 67000350017
9                                           0.2, 0.2, 0.2, 0.2, 0.2 67000350049
10 0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667, 0.1666667 67000350018
   COUNTYNAME TOWNNAME VILLNAME       VILLENG COUNTYID COUNTYCODE TOWNID
1      臺南市   安南區   青草里  Qingcao Vil.        D      67000    D06
2      臺南市   仁德區   保安里   Bao'an Vil.        D      67000    D32
3      臺南市   中西區   赤嵌里  Chihkan Vil.        D      67000    D08
4      臺南市     南區   大成里  Dacheng Vil.        D      67000    D02
5      臺南市   安南區   城北里 Chengbei Vil.        D      67000    D06
6      臺南市   安南區   城南里 Chengnan Vil.        D      67000    D06
7      臺南市   中西區   法華里    Fahua Vil.        D      67000    D08
8      臺南市   安南區   海南里   Hainan Vil.        D      67000    D06
9      臺南市   安南區   國安里   Guo'an Vil.        D      67000    D06
10     臺南市   安南區   溪心里    Xixin Vil.        D      67000    D06
   TOWNCODE incidents                       geometry
1  67000350         2 POLYGON ((120.1176 23.08387...
2  67000270        19 POLYGON ((120.2304 22.93544...
3  67000370       111 POLYGON ((120.2012 22.99966...
4  67000330        29 POLYGON ((120.1985 22.98147...
5  67000350         1 POLYGON ((120.1292 23.06512...
6  67000350        10 POLYGON ((120.1246 23.06904...
7  67000370        38 POLYGON ((120.2094 22.98452...
8  67000350        44 POLYGON ((120.175 23.02218,...
9  67000350       112 POLYGON ((120.1866 23.02766...
10 67000350        65 POLYGON ((120.1834 23.06086...</code></pre>
</div>
</div>
<p>Let’s understand this. We can see that there is a list of neighbours for each village. For example, the first village has neighbours 6, 118, 160. And each of the neighbours had equal weight, with each neighbour having the same influence over the village</p>
</section>
<section id="computing-global-moran-i" class="level2">
<h2 class="anchored" data-anchor-id="computing-global-moran-i">4.2 <strong>Computing Global Moran’ I</strong></h2>
<p><strong>What is Global Moran’ I?</strong></p>
<p>Global Moran’s I is a statistical measure used to assess spatial autocorrelation in data measured across a geographic area. We are trying to assess whether similar values cluster close together, or are further away.</p>
<p>Value’s meaning:</p>
<ol type="1">
<li>A <strong>positive value</strong> indicates <strong>positive spatial correlation</strong> and that similar values cluster together.</li>
<li>A <strong>negative value</strong> indicates <strong>negative spatial correlation</strong> and that similar values being spatially apart.</li>
<li>A value <strong>near zero</strong> implies a <strong>random spatial distribution</strong> of the values, showing no significant autocorrelation</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>moranI <span class="ot">&lt;-</span> <span class="fu">global_moran</span>(wm_q<span class="sc">$</span>incidents,</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>                       wm_q<span class="sc">$</span>nb,</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>                       wm_q<span class="sc">$</span>wt)</span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(moranI)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 2
 $ I: num 0.464
 $ K: num 5.66</code></pre>
</div>
</div>
<p>The Global Moran’s I statistic was 0.464. This suggests a positive spatial autocorrelation. This means that similar values of <strong><code>incidents</code></strong> tend to be clustered together geographically in your dataset.</p>
<p>Not only do we Global Moran’s I statistic, we want to assess the statistical significance of the Moran’s I statistic if the spatial pattern is unlikely to have occurred by chance.</p>
</section>
<section id="performing-global-morans-i-test" class="level2">
<h2 class="anchored" data-anchor-id="performing-global-morans-i-test">4.3 <strong>Performing Global Moran’s I test</strong></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">global_moran_test</span>(wm_q<span class="sc">$</span>incidents,</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>                       wm_q<span class="sc">$</span>nb,</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>                       wm_q<span class="sc">$</span>wt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Moran I test under randomisation

data:  x  
weights: listw    

Moran I statistic standard deviate = 12.705, p-value &lt; 2.2e-16
alternative hypothesis: greater
sample estimates:
Moran I statistic       Expectation          Variance 
      0.464386792      -0.003906250       0.001358653 </code></pre>
</div>
</div>
<p>Based on analysis result, sicne p value which is 2.2e-16 and is much lower than the confidence interval value of 0.05, we have enough statistical evidence to reject the null hypothesis that states that points are randomly distributed. It allows us to infer that the distribution resembles clustering because the Moran I value was over 0.4.</p>
<p>As it is 0. we can infer there is clustering, but the value is not tool large- so there is clustering but at very distinct places. So we need to execute local moran to detect the specific areas with hotspots/coldspots , clusters and outliers.</p>
</section>
<section id="performing-global-morans-permutation-test" class="level2">
<h2 class="anchored" data-anchor-id="performing-global-morans-permutation-test">4.4 <strong>Performing Global Moran’s permutation test</strong></h2>
<p>We do this to double confirm that there indeed is clustering and that the incidents of dengue are not randomly distributed. We do this through <u>monte carlo simulations</u><strong>.</strong></p>
<p><strong>How are Monte Carlo Simulations conducted?</strong></p>
<ol type="1">
<li><p><strong>Start with Real Spatial Data</strong>: We have a map with data points, each representing a value of interest, like dengue incidents in different villages.</p></li>
<li><p><strong>The Question</strong>: We want to know if dengue incidents in one village are related to high dengue incidents in neighboring village (positive spatial autocorrelation), or if it’s just random.</p></li>
<li><p><strong>Creating a Simulated World</strong>:</p></li>
</ol>
<pre><code>-   Imagine we take the map and erase all the dengue incidents data.

-   Then, we redistribute those dengue incidents data randomly across the map. This means we're shuffling the data points so they no longer have their original spatial pattern. Each village gets a dengue incidents data, but now it's randomly assigned, not based on the real-world data.</code></pre>
<ol start="4" type="1">
<li><strong>Calculating Moran’s I for the Simulated World</strong>:</li>
</ol>
<pre><code>1.  WE do simulations (which represent a world of randomness without any spatial pattern),

2.  With this shuffled map, we calculate Moran's I, a statistic that measures how much the dengue incidents data in one village is similar to the rates in nearby villages.

3.  This calculation gives us a sense of whether the shuffled (randomized) data still shows any pattern of similar values being close together.</code></pre>
<ol start="5" type="1">
<li><p><strong>Repeat the Simulation Multiple Times</strong>:</p>
<ul>
<li><p>We don’t do this process just once. We repeat it many times, each time reshuffling the data and calculating a new Moran’s I.</p></li>
<li><p>This creates a bunch of Moran’s I values from worlds that are similar to ours but with randomized crime rates.</p></li>
</ul></li>
<li><p><strong>Compare the Real World to the Simulated Worlds</strong>:</p></li>
</ol>
<pre><code>-   Now, we compare the Moran's I you calculated from your real data to the range of Moran's I values you got from your simulations.

-   If the real Moran's I is much higher than what we mostly see in the simulations, it suggests that the pattern in your real data is not random; it's statistically significant.</code></pre>
<ol start="7" type="1">
<li>It is alway a good practice to use&nbsp;<code>set.seed()</code>&nbsp;before performing simulation. This is to ensure that the computation is reproducible.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next,&nbsp;<code>global_moran_perm()</code>&nbsp;is used to perform Monte Carlo simulation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">global_moran_perm</span>(wm_q<span class="sc">$</span>incidents,</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>                       wm_q<span class="sc">$</span>nb,</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>                       wm_q<span class="sc">$</span>wt,</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">nsim =</span> <span class="dv">99</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Monte-Carlo simulation of Moran I

data:  x 
weights: listw  
number of simulations + 1: 100 

statistic = 0.46439, observed rank = 100, p-value &lt; 2.2e-16
alternative hypothesis: two.sided</code></pre>
</div>
</div>
<p>In the context of Monte Carlo simulations, the rank of the observed Moran’s I value (0.46439) among the Moran’s I values generated from the simulated random datasets indicates its position. A rank of 100 out of 100 means that the observed Moran’s I was the highest among all simulated values, suggesting that the observed spatial autocorrelation is exceptionally strong compared to what would be expected by chance.</p>
<p>The very low p value also allows us to reject the null hypothesis and deduce that the spatial autocorrelation is unlikely to have occurred by chance.</p>
<p>We can infer that the spatial distribution shows sign of clustering.</p>
<p>Now, let’s use local moran to identify areas where clustering occurred.</p>
</section>
<section id="computing-local-morans-i" class="level2">
<h2 class="anchored" data-anchor-id="computing-local-morans-i">4.5 <strong>Computing local Moran’s I</strong></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>lisa <span class="ot">&lt;-</span> wm_q <span class="sc">%&gt;%</span> </span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">local_moran =</span> <span class="fu">local_moran</span>(</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>    incidents, nb, wt, <span class="at">nsim =</span> <span class="dv">99</span>),</span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">.before =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(local_moran)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="visualisng-local-morans-i" class="level3">
<h3 class="anchored" data-anchor-id="visualisng-local-morans-i">4.5.1 <strong>Visualisng local Moran’s I</strong></h3>
<p>Let’s visualise!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(lisa) <span class="sc">+</span></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"ii"</span>) <span class="sc">+</span> </span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_view</span>(<span class="at">set.zoom.limits =</span> <span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">8</span>)) <span class="sc">+</span></span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"local Moran's I of incidents"</span>,</span>
<span id="cb79-7"><a href="#cb79-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex02_files/figure-html/unnamed-chunk-60-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Let’s analyse this visualisation.</p>
<p><strong>The dark green areas</strong> that also surrounded by dark green or lighter green areas have high local moran’s i values, indicating strong spatial correlation, and that these areas and immediate neighbours have similarly high values.</p>
<p>The same middle part also has many <strong>orange areas</strong>, that have low local moran’s I values. This means that there is a stark difference between the number of dengue incidents there compared to villages near it - and <em>this makes sense.</em></p>
<p>From our first map, we know that the middle area is concentrated with dengue incidents.</p>
<p>The middle area is so dense with packed with many small small villages. It makes sense that some villages would be concentrated with incidents, and another village right next to it might not, and this can result in a stark difference in a stark difference in value and negative local moran.</p>
</section>
<section id="visualisng-p-value-of-local-morans-i" class="level3">
<h3 class="anchored" data-anchor-id="visualisng-p-value-of-local-morans-i">4.5.1 <strong>Visualisng p value of local Moran’s I</strong></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(lisa) <span class="sc">+</span></span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"p_ii_sim"</span>) <span class="sc">+</span> </span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>   <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"p-value of local Moran's I"</span>,</span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex02_files/figure-html/unnamed-chunk-61-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Light Brown Areas</strong> : These areas have low p-values, indicating that the Local Moran’s I values for these areas are statistically significant. The closer the p-value is to 0, the stronger the evidence against the null hypothesis (which states that there is no spatial autocorrelation). Thus, areas in this range are likely to represent significant spatial clusters or outliers.</p>
<p><strong>Darker Brown Areas</strong> : As the colors get darker (moving towards the 1.0 end of the scale), the p-values increase, suggesting weaker evidence against the null hypothesis. Areas with p-values closer to 1.0 suggest that the local spatial patterns might be due to random chance rather than a significant spatial process.</p>
</section>
<section id="visuaising-local-morans-i-and-p-value" class="level3">
<h3 class="anchored" data-anchor-id="visuaising-local-morans-i-and-p-value">4.5.2 <strong>Visuaising local Moran’s I and p-value</strong></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>map1 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(lisa) <span class="sc">+</span></span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"ii"</span>) <span class="sc">+</span> </span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_view</span>(<span class="at">set.zoom.limits =</span> <span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">8</span>)) <span class="sc">+</span></span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"local Moran's I of GDPPC"</span>,</span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.8</span>)</span>
<span id="cb81-8"><a href="#cb81-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-9"><a href="#cb81-9" aria-hidden="true" tabindex="-1"></a>map2 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(lisa) <span class="sc">+</span></span>
<span id="cb81-10"><a href="#cb81-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"p_ii"</span>,</span>
<span id="cb81-11"><a href="#cb81-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.001</span>, <span class="fl">0.01</span>, <span class="fl">0.05</span>, <span class="dv">1</span>),</span>
<span id="cb81-12"><a href="#cb81-12" aria-hidden="true" tabindex="-1"></a>              <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"0.001"</span>, <span class="st">"0.01"</span>, <span class="st">"0.05"</span>, <span class="st">"Not sig"</span>)) <span class="sc">+</span> </span>
<span id="cb81-13"><a href="#cb81-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb81-14"><a href="#cb81-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"p-value of local Moran's I"</span>,</span>
<span id="cb81-15"><a href="#cb81-15" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title.size =</span> <span class="fl">0.8</span>)</span>
<span id="cb81-16"><a href="#cb81-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-17"><a href="#cb81-17" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(map1, map2, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex02_files/figure-html/unnamed-chunk-62-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="visualising-lisa-map" class="level2">
<h2 class="anchored" data-anchor-id="visualising-lisa-map">4.6 <strong>Visualising LISA map</strong></h2>
<p>Let’s plot the LISA map to check for of outliers and clusters.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>lisa_sig <span class="ot">&lt;-</span> lisa  <span class="sc">%&gt;%</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(p_ii <span class="sc">&lt;</span> <span class="fl">0.05</span>)</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(lisa) <span class="sc">+</span></span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>() <span class="sc">+</span></span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb82-7"><a href="#cb82-7" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(lisa_sig) <span class="sc">+</span></span>
<span id="cb82-8"><a href="#cb82-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"mean"</span>) <span class="sc">+</span> </span>
<span id="cb82-9"><a href="#cb82-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex02_files/figure-html/unnamed-chunk-63-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This again corroborates with our first map that shows the distribution of dengue cases , and the area around the middle part having high number of cases can be likened to the high-high villages around the middle of the city.</p>
</section>
<section id="hot-spot-and-cold-spot-area-analysis-hcsa" class="level2">
<h2 class="anchored" data-anchor-id="hot-spot-and-cold-spot-area-analysis-hcsa">4.7 <strong>Hot Spot and Cold Spot Area Analysis (HCSA)</strong></h2>
<p>HCSA uses spatial weights to identify locations of statistically significant hot spots and cold spots in an spatially weighted attribute that are in proximity to one another based on a calculated distance. The analysis groups features when similar high (hot) or low (cold) values are found in a cluster. The polygon features usually represent administration boundaries or a custom grid structure.</p>
<section id="computing-local-gi-statistics" class="level3">
<h3 class="anchored" data-anchor-id="computing-local-gi-statistics">4.7.1 Computing Local Gi* Statistics</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>tryNow1 <span class="ot">&lt;-</span> tryNow <span class="sc">%&gt;%</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(incidents))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We will need to derive a spatial weight matrix before we can compute local Gi* statistics.</p>
<p>It specifies which areas are neighbors and how strongly they should be weighted based on distance.</p>
<p>High positive Gi∗​ values indicate a clustering of high values (hotspots), while low negative Gi∗​ values indicate a clustering of low values (coldspots).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>wm_idw <span class="ot">&lt;-</span> tryNow1 <span class="sc">%&gt;%</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">nb =</span> <span class="fu">st_contiguity</span>(geometry),</span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">wts =</span> <span class="fu">st_inverse_distance</span>(nb, geometry,</span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">scale =</span> <span class="dv">1</span>,</span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">alpha =</span> <span class="dv">1</span>),</span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">.before =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we are calculating the Local GI* Statistic</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>HCSA <span class="ot">&lt;-</span> wm_idw <span class="sc">%&gt;%</span> </span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">local_Gi =</span> <span class="fu">local_gstar_perm</span>(</span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>    incidents, nb, wt, <span class="at">nsim =</span> <span class="dv">99</span>),</span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">.before =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unnest</span>(local_Gi)</span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a>HCSA</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 257 features and 22 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 120.0627 ymin: 22.89401 xmax: 120.2925 ymax: 23.09144
Geodetic CRS:  TWD97
# A tibble: 257 × 23
   gi_star cluster    e_gi    var_gi std_dev p_value p_sim p_folded_sim skewness
     &lt;dbl&gt; &lt;fct&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;        &lt;dbl&gt;    &lt;dbl&gt;
 1  -2.35  Low     0.00295   1.95e-6 -1.93   0.0535   0.02         0.01   0.417 
 2  -2.07  Low     0.00334   1.39e-6 -1.73   0.0831   0.04         0.02   1.08  
 3   0.369 High    0.00424   9.47e-7  0.0302 0.976    0.98         0.49   0.319 
 4   0.366 Low     0.00362   1.38e-6  0.591  0.555    0.58         0.29   0.487 
 5  -2.65  Low     0.00292   1.01e-6 -2.68   0.00742  0.02         0.01   0.870 
 6  -3.17  Low     0.00351   1.18e-6 -3.03   0.00242  0.02         0.01  -0.0143
 7  -1.25  Low     0.00342   1.60e-6 -0.983  0.325    0.32         0.16   0.650 
 8  -0.277 Low     0.00386   8.08e-7 -0.244  0.807    0.88         0.44   0.434 
 9   1.53  High    0.00438   1.42e-6  1.21   0.228    0.32         0.16   0.501 
10  -1.47  Low     0.00398   1.30e-6 -1.57   0.117    0.1          0.05   0.396 
# ℹ 247 more rows
# ℹ 14 more variables: kurtosis &lt;dbl&gt;, nb &lt;nb&gt;, wts &lt;list&gt;, VILLCODE &lt;chr&gt;,
#   COUNTYNAME &lt;chr&gt;, TOWNNAME &lt;chr&gt;, VILLNAME &lt;chr&gt;, VILLENG &lt;chr&gt;,
#   COUNTYID &lt;chr&gt;, COUNTYCODE &lt;chr&gt;, TOWNID &lt;chr&gt;, TOWNCODE &lt;chr&gt;,
#   incidents &lt;int&gt;, geometry &lt;POLYGON [°]&gt;</code></pre>
</div>
</div>
<p>Let’s visualise it!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(HCSA) <span class="sc">+</span></span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_fill</span>(<span class="st">"gi_star"</span>) <span class="sc">+</span> </span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_view</span>(<span class="at">set.zoom.limits =</span> <span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">8</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex02_files/figure-html/unnamed-chunk-67-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Let’s also add the first map that showed the distribution of the dengue incidents to understand the HCSA map better:</p>
<p><img src="images/clipboard-57072497.png" class="img-fluid"></p>
<p><strong>Dark Red villages :</strong></p>
<p>These are likely the coldspots, areas where the local ∗Gi∗​ values are significantly lower than the mean, indicating a clustering of low values.</p>
<p>This makes sense when we see the purple distribution map that shows how the outer areas have the lowest number of dengue cases, and they are all near each other.</p>
<p><strong>Dark green and Green Villages (2-6) :</strong></p>
<p>These are the villages around the middle of the city that are hotspots, where the local Gi* values are significantly higher than the mean, meanning that there is a clustering of high values which is corroborated by the purple graph too. In the area around the middle of the city, multiple villages close together have high number of dengue cases.</p>
<hr>
<p>Here we have done Hot spot cold spot analysis and calculated Gi* values <strong>without taking time into consideration</strong>. We do not consider how many dengue incidents happened per week per village, but considered just the number of incidents per village in totaily.</p>
</section>
</section>
</section>
<section id="creating-a-time-series-cube" class="level1">
<h1>Creating a Time Series Cube</h1>
<p>Here we will create a time series cube to show the number of dengue incidents per week per village.</p>
<p>First, let’s remove the columns with all the NAs, which is NOTE.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>taiwan_filtered1 <span class="ot">&lt;-</span> taiwan_filtered <span class="sc">%&gt;%</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>NOTE)</span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>taiwan_filtered1 <span class="ot">&lt;-</span> tidyr<span class="sc">::</span><span class="fu">drop_na</span>(taiwan_filtered1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now let’s see the number of dengue incidents per village per week. As we do not need this to be spatial data, let’s remove the geometry call.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dengue_pervillage_week)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 3 fields
Geometry type: GEOMETRY
Dimension:     XY
Bounding box:  xmin: 120.2534 ymin: 22.98918 xmax: 120.2721 ymax: 22.994
Geodetic CRS:  TWD97
# A tibble: 6 × 4
  VILLCODE     week incidents                                           geometry
  &lt;chr&gt;       &lt;dbl&gt;     &lt;int&gt;                                     &lt;GEOMETRY [°]&gt;
1 67000270001    33         1                          POINT (120.2583 22.99218)
2 67000270001    34         1                          POINT (120.2612 22.99222)
3 67000270001    35         2 MULTIPOINT ((120.2625 22.994), (120.2668 22.98918…
4 67000270001    36         3 MULTIPOINT ((120.2555 22.99274), (120.2574 22.989…
5 67000270001    37         5 MULTIPOINT ((120.2555 22.99274), (120.2591 22.992…
6 67000270001    38         4 MULTIPOINT ((120.2534 22.99117), (120.2639 22.991…</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>dengue_pervillage_week  <span class="ot">&lt;-</span> <span class="fu">st_set_geometry</span>(dengue_pervillage_week , <span class="cn">NULL</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can see that not every village has every week, so let’s create that.</p>
<p>We have created a data frame previously where each village code has a corresponding week from 31-50. Let’s see that</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(villagecode_week_set)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     VILLCODE week
1 67000350032   31
2 67000270011   31
3 67000370005   31
4 67000330004   31
5 67000350028   31
6 67000350030   31</code></pre>
</div>
</div>
<p>Now let’s combine the villagecode_week_set with the actual number of incidents per week per village. And the weeks that do not have any incidents will be kept as 0.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>final_set1 <span class="ot">&lt;-</span> <span class="fu">left_join</span>(villagecode_week_set</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>, dengue_pervillage_week, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"VILLCODE"</span>, <span class="st">"week"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">replace</span>(<span class="fu">is.na</span>(.), <span class="dv">0</span>)  <span class="co"># Replace NA values with 0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s double check to see that all villages in taiwan_filtered(Geospatial data) are in our dengue (aspatial data)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>extra_observation <span class="ot">&lt;-</span> <span class="fu">anti_join</span>(taiwan_filtered1, final_set1, <span class="at">by =</span> <span class="st">"VILLCODE"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(final_set1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "data.frame"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(taiwan_filtered1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "sf"         "data.frame"</code></pre>
</div>
</div>
<p>This is not a tibble data frame as said by prof in piazza. So,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>final_set1 <span class="ot">&lt;-</span> <span class="fu">as.tibble</span>(final_set1)</span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(final_set1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "tbl_df"     "tbl"        "data.frame"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>dengue_st <span class="ot">&lt;-</span> <span class="fu">spacetime</span>(final_set1, taiwan_filtered1</span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>                       ,</span>
<span id="cb102-3"><a href="#cb102-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">.loc_col =</span> <span class="st">"VILLCODE"</span>,</span>
<span id="cb102-4"><a href="#cb102-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">.time_col =</span> <span class="st">"week"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is_spacetime_cube</span>(dengue_st)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<section id="computing-gi" class="level2">
<h2 class="anchored" data-anchor-id="computing-gi"><strong>Computing Gi*</strong></h2>
<p>Next, we will compute the local Gi* statistics, but this time taking the number of incidents, per village ,per week - <strong>its a temporal analysis as well.</strong></p>
<section id="deriving-the-spatial-weights" class="level3">
<h3 class="anchored" data-anchor-id="deriving-the-spatial-weights"><strong>Deriving the spatial weights</strong></h3>
<p>The code chunk below will be used to identify neighbors and to derive an inverse distance weights.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a>dengue_st_nb <span class="ot">&lt;-</span> dengue_st <span class="sc">%&gt;%</span></span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">activate</span>(<span class="st">"geometry"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">nb =</span> <span class="fu">include_self</span>(<span class="fu">st_contiguity</span>(geometry)),</span>
<span id="cb105-4"><a href="#cb105-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">wt =</span> <span class="fu">st_inverse_distance</span>(nb, geometry,</span>
<span id="cb105-5"><a href="#cb105-5" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">scale =</span> <span class="dv">1</span>,</span>
<span id="cb105-6"><a href="#cb105-6" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">alpha =</span> <span class="dv">1</span>),</span>
<span id="cb105-7"><a href="#cb105-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">.before =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb105-8"><a href="#cb105-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_nbs</span>(<span class="st">"nb"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb105-9"><a href="#cb105-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_wts</span>(<span class="st">"wt"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that this dataset now has neighbors and weights for each time-slice.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dengue_st_nb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  VILLCODE     week incidents nb        wt       
  &lt;chr&gt;       &lt;dbl&gt;     &lt;dbl&gt; &lt;list&gt;    &lt;list&gt;   
1 67000350032    31         0 &lt;int [4]&gt; &lt;dbl [4]&gt;
2 67000270011    31         1 &lt;int [6]&gt; &lt;dbl [6]&gt;
3 67000370005    31         0 &lt;int [9]&gt; &lt;dbl [9]&gt;
4 67000330004    31         0 &lt;int [7]&gt; &lt;dbl [7]&gt;
5 67000350028    31         0 &lt;int [5]&gt; &lt;dbl [5]&gt;
6 67000350030    31         0 &lt;int [8]&gt; &lt;dbl [8]&gt;</code></pre>
</div>
</div>
<p>This lists the neighbours of each village, and the spatial weight of each village.</p>
</section>
</section>
<section id="computing-gi-1" class="level2">
<h2 class="anchored" data-anchor-id="computing-gi-1"><strong>Computing Gi*</strong></h2>
<p>We can use these new columns to manually calculate the local Gi* for each village. We can do this by grouping by&nbsp;<em>week</em> and using&nbsp;<code>local_gstar_perm()</code>&nbsp;of sfdep package. After which, we&nbsp;<code>use unnest()</code>&nbsp;to unnest&nbsp;<em>gi_star</em>&nbsp;column of the newly created&nbsp;<em>gi_starts</em>&nbsp;data.frame.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a>gi_stars <span class="ot">&lt;-</span> dengue_st_nb <span class="sc">%&gt;%</span> </span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(week) <span class="sc">%&gt;%</span> </span>
<span id="cb108-3"><a href="#cb108-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">gi_star =</span> <span class="fu">local_gstar_perm</span>(</span>
<span id="cb108-4"><a href="#cb108-4" aria-hidden="true" tabindex="-1"></a>    incidents, nb, wt)) <span class="sc">%&gt;%</span> </span>
<span id="cb108-5"><a href="#cb108-5" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">unnest</span>(gi_star)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Inspect the structure of 'nb' to ensure it's a valid neighbors list</span></span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dengue_st_nb<span class="sc">$</span>nb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 5160
 $ : int [1:4] 1 6 118 160
 $ : int [1:6] 2 126 128 138 168 222
 $ : int [1:9] 3 68 69 172 181 184 185 188 200
 $ : int [1:7] 4 94 97 100 104 182 207
 $ : int [1:5] 5 12 13 249 255
 $ : int [1:8] 1 6 12 13 118 160 165 249
 $ : int [1:5] 7 54 98 99 201
 $ : int [1:11] 8 9 73 75 115 125 144 156 157 166 ...
 $ : int [1:6] 8 9 110 115 125 166
 $ : int [1:7] 10 11 159 161 166 236 258
 $ : int [1:6] 10 11 159 161 167 242
 $ : int [1:5] 5 6 12 13 249
 $ : int [1:7] 5 6 12 13 14 118 255
 $ : int [1:4] 13 14 118 255
 $ : int [1:5] 15 16 18 139 226
 $ : int [1:5] 15 16 17 139 226
 $ : int [1:6] 16 17 22 139 226 240
 $ : int [1:5] 15 18 139 209 210
 $ : int [1:7] 19 23 24 149 151 241 246
 $ : int [1:4] 20 21 23 241
 $ : int [1:9] 20 21 23 140 145 197 198 208 241
 $ : int [1:9] 17 22 24 139 141 148 150 151 240
 $ : int [1:8] 19 20 21 23 24 140 145 241
 $ : int [1:10] 19 22 23 24 141 142 145 151 164 248
 $ : int [1:5] 25 26 169 211 248
 $ : int [1:6] 25 26 163 211 213 248
 $ : int [1:6] 27 28 128 131 136 152
 $ : int [1:6] 27 28 29 36 136 152
 $ : int [1:6] 28 29 30 32 36 152
 $ : int [1:9] 29 30 31 32 34 39 92 152 153
 $ : int [1:7] 30 31 33 39 92 95 98
 $ : int [1:7] 29 30 32 34 36 39 41
 $ : int [1:5] 31 33 37 39 98
 $ : int [1:8] 30 32 34 36 39 41 42 47
 $ : int [1:6] 35 36 38 44 131 137
 $ : int [1:11] 28 29 32 34 35 36 41 44 50 136 ...
 $ : int [1:6] 33 37 39 51 54 98
 $ : int [1:5] 35 38 43 44 131
 $ : int [1:11] 30 31 32 33 34 37 39 42 47 51 ...
 $ : int [1:5] 40 43 45 131 135
 $ : int [1:9] 32 34 36 41 42 44 46 47 50
 $ : int [1:6] 34 39 41 42 47 51
 $ : int [1:6] 38 40 43 44 45 131
 $ : int [1:9] 35 36 38 41 43 44 45 50 52
 $ : int [1:9] 40 43 44 45 48 52 135 225 226
 $ : int [1:6] 41 46 47 49 50 56
 $ : int [1:12] 34 39 41 42 46 47 49 50 51 53 ...
 $ : int [1:5] 45 48 52 57 226
 $ : int [1:8] 46 47 49 53 55 56 58 60
 $ : int [1:10] 36 41 44 46 47 50 52 56 63 64
 $ : int [1:7] 37 39 42 47 51 54 59
 $ : int [1:8] 44 45 48 50 52 57 63 64
 $ : int [1:5] 47 49 53 55 60
 $ : int [1:9] 7 37 39 51 54 59 98 201 218
 $ : int [1:5] 49 53 55 58 60
 $ : int [1:7] 46 49 50 56 58 61 63
 $ : int [1:5] 48 52 57 64 226
 $ : int [1:7] 49 55 56 58 60 61 67
 $ : int [1:8] 47 51 54 59 60 62 188 218
 $ : int [1:10] 47 49 53 55 58 59 60 62 67 68
 $ : int [1:5] 56 58 61 63 67
 $ : int [1:6] 59 60 62 67 68 188
 $ : int [1:9] 50 52 56 61 63 64 65 66 67
 $ : int [1:11] 50 52 57 63 64 65 146 226 239 240 ...
 $ : int [1:6] 63 64 65 66 192 239
 $ : int [1:5] 63 65 66 67 192
 $ : int [1:10] 58 60 61 62 63 66 67 68 192 214
 $ : int [1:9] 3 60 62 67 68 69 70 188 214
 $ : int [1:7] 3 68 69 70 172 176 177
 $ : int [1:7] 68 69 70 175 177 214 215
 $ : int [1:5] 71 72 73 154 156
 $ : int [1:9] 71 72 73 75 154 189 196 203 221
 $ : int [1:6] 8 71 72 73 75 156
 $ : int [1:8] 74 76 140 173 174 178 179 190
 $ : int [1:8] 8 72 73 75 113 125 203 217
 $ : int [1:6] 74 76 109 111 140 173
 $ : int [1:3] 77 78 79
 $ : int [1:6] 77 78 79 80 132 223
 $ : int [1:4] 77 78 79 80
 $ : int [1:5] 78 79 80 132 133
 $ : int [1:4] 81 82 83 133
 $ : int [1:8] 81 82 83 84 86 128 133 153
 $ : int [1:5] 81 82 83 84 91
 $ : int [1:7] 82 83 84 85 86 87 91
 $ : int [1:8] 84 85 86 87 89 91 102 171
 $ : int [1:8] 82 84 85 86 87 88 100 153
 $ : int [1:7] 84 85 86 87 88 90 171
 $ : int [1:6] 86 87 88 90 94 100
 $ : int [1:6] 85 89 91 93 102 171
 $ : int [1:5] 87 88 90 94 171
 $ : int [1:8] 83 84 85 89 91 102 120 143
 $ : int [1:5] 30 31 92 95 153
 $ : int [1:5] 89 93 96 102 171
 $ : int [1:7] 4 88 90 94 97 100 171
 $ : int [1:7] 31 92 95 98 99 100 153
 $ : int [1:8] 93 96 97 101 102 103 104 171
 $ : int [1:6] 4 94 96 97 104 171
 $ : int [1:8] 7 31 33 37 54 95 98 99
 $ : int [1:7] 7 95 98 99 100 201 207
  [list output truncated]
 - attr(*, "class")= chr [1:2] "list" "nb"</code></pre>
</div>
</div>
</section>
</section>
<section id="mann-kendall-test" class="level1">
<h1><strong>Mann-Kendall Test</strong></h1>
<p>The Mann-Kendall Test is a non-parametric statistical test used to identify trends in a dataset without assuming the data follows a specific distribution.</p>
<p>It tests for an upward or downward trend in a time series dataset.</p>
<p>The test determines whether the observed sum of scores is significantly different from what would be expected by chance, indicating a trend.</p>
<p>With these Gi* measures we can then evaluate each location for a trend using the Mann-Kendall test. The code chunk below uses Changsha county.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a>cbg <span class="ot">&lt;-</span> gi_stars <span class="sc">%&gt;%</span> </span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb111-3"><a href="#cb111-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(VILLCODE <span class="sc">==</span> <span class="st">"67000350050"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb111-4"><a href="#cb111-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(VILLCODE, week, gi_star)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> cbg, </span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> week, </span>
<span id="cb112-3"><a href="#cb112-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">y =</span> gi_star)) <span class="sc">+</span></span>
<span id="cb112-4"><a href="#cb112-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb112-5"><a href="#cb112-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex02_files/figure-html/unnamed-chunk-83-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The peaks, where the ∗G*∗ values rise above 1, suggest potential hotspots. This could mean that during these weeks, the village represented by <strong><code>VILLCODE = "67000350050"</code></strong> was experiencing higher than usual dengue incidence relative to its neighbors.</p>
<p>Conversely, when the ∗G*∗ values dip below -1, this could be indicative of coldspots. It could imply that during these weeks, the village had lower dengue incidence relative to its neighbors.</p>
<p>Most of the time, until about week 47, the ∗G*∗ values were always above 1, indicaitng that there were more dengue incidents in this village compared to the other villages most of the time.</p>
<p>And this is corroborated by the fact that is village is from D06, which we can see is the town with the second most incidents from the graph below.</p>
<p>We can also see that it is the village with the second most number of incidents from the data frame dengue_per_village</p>
<p>There are two prominent peaks after the midpoint of the 20 week period, indicating that there were more dengue incidents in this village compared to the other villages in that time period.</p>
<p><img src="images/clipboard-1535541130.png" class="img-fluid"></p>
<section id="performing-emerging-hotspot-analysis" class="level2">
<h2 class="anchored" data-anchor-id="performing-emerging-hotspot-analysis"><strong>Performing Emerging Hotspot Analysis</strong></h2>
<p>Lastly, we will perform EHSA analysis by using&nbsp;<a href="https://sfdep.josiahparry.com/reference/emerging_hotspot_analysis.html"><code>emerging_hotspot_analysis()</code></a>&nbsp;of sfdep package. It takes a spacetime object x , and the quoted name of the variable of interest for .var argument. The k argument is used to specify the number of time lags which is set to 1 by default. Lastly, nsim map numbers of simulation to be performed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="co">#ehsa &lt;- emerging_hotspot_analysis(</span></span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a>  <span class="co">#x = dengue_st, </span></span>
<span id="cb113-3"><a href="#cb113-3" aria-hidden="true" tabindex="-1"></a>  <span class="co">#.var = "incidents", </span></span>
<span id="cb113-4"><a href="#cb113-4" aria-hidden="true" tabindex="-1"></a>  <span class="co">#k = 1, </span></span>
<span id="cb113-5"><a href="#cb113-5" aria-hidden="true" tabindex="-1"></a>  <span class="co">#nsim = 99</span></span>
<span id="cb113-6"><a href="#cb113-6" aria-hidden="true" tabindex="-1"></a><span class="co">#)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="co">#write_rds(ehsa, "../../data/rds/ehsa.rds")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a>ehsa <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"../../data/rds/ehsa.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="visualising-the-distribution-of-ehsa-classes" class="level3">
<h3 class="anchored" data-anchor-id="visualising-the-distribution-of-ehsa-classes"><strong>Visualising the distribution of EHSA classes</strong></h3>
<p>In the code chunk below, ggplot2 functions ised used to reveal the distribution of EHSA classes as a bar chart.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr) <span class="co"># for str_wrap function</span></span>
<span id="cb116-3"><a href="#cb116-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb116-4"><a href="#cb116-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> ehsa, <span class="fu">aes</span>(<span class="at">x =</span> classification)) <span class="sc">+</span></span>
<span id="cb116-5"><a href="#cb116-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb116-6"><a href="#cb116-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb116-7"><a href="#cb116-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>, <span class="at">angle =</span> <span class="dv">0</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb116-8"><a href="#cb116-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">labels =</span> <span class="cf">function</span>(x) <span class="fu">str_wrap</span>(x, <span class="at">width =</span> <span class="dv">10</span>)) <span class="co"># Adjust 'width' as needed</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex02_files/figure-html/unnamed-chunk-87-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here, there are a high number of oscillating hotspots. These locations alternate being hotspots and coldspots during different time periods. For example a village with the villagecode 67000330004 is like so.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>