<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2024-02-04">

<title>IS415-GAA - Take-home Exercise 1 : Application of Spatial Point Patterns Analysis to discover the geographical distribution of Grab hailing services in Singapore</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">IS415-GAA</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../Hands-On_Ex/Hands-on_Ex01/Hands-on_Ex01.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-On_Ex/Hands-on_Ex02/Hands-on_Ex02.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-On_Ex/Hand-on_Ex03/Hands-on_Ex03.html" rel="" target="">
 <span class="dropdown-text">Hands-on Exercise 3</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">In-class Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class-Ex02/In-class_Ex02.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class-Ex03/In-class-Ex03.html" rel="" target="">
 <span class="dropdown-text">In-class Exercise 3</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Take home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.html" rel="" target="">
 <span class="dropdown-text">Take home exercise 1</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#install-load-packages" id="toc-install-load-packages" class="nav-link active" data-scroll-target="#install-load-packages">1 Install &amp; Load Packages</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">2 Data</a>
  <ul class="collapse">
  <li><a href="#data-download" id="toc-data-download" class="nav-link" data-scroll-target="#data-download">2.1 Data Download</a></li>
  <li><a href="#data-import" id="toc-data-import" class="nav-link" data-scroll-target="#data-import">2.2 Data Import</a></li>
  <li><a href="#data-wrangling" id="toc-data-wrangling" class="nav-link" data-scroll-target="#data-wrangling">2.3 Data Wrangling</a>
  <ul class="collapse">
  <li><a href="#master-plan-2019-subzone-boundary-1" id="toc-master-plan-2019-subzone-boundary-1" class="nav-link" data-scroll-target="#master-plan-2019-subzone-boundary-1">2.3.1 Master Plan 2019 Subzone Boundary</a></li>
  <li><a href="#road-data-set-1" id="toc-road-data-set-1" class="nav-link" data-scroll-target="#road-data-set-1">2.3.2 Road Data Set</a></li>
  <li><a href="#grab-posisi-1" id="toc-grab-posisi-1" class="nav-link" data-scroll-target="#grab-posisi-1">2.3.3 Grab Posisi</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#visualization-spatial-pattern-analysis" id="toc-visualization-spatial-pattern-analysis" class="nav-link" data-scroll-target="#visualization-spatial-pattern-analysis">3.Visualization &amp; Spatial Pattern Analysis</a>
  <ul class="collapse">
  <li><a href="#location-visualizations" id="toc-location-visualizations" class="nav-link" data-scroll-target="#location-visualizations">3.1 Location Visualizations</a>
  <ul class="collapse">
  <li><a href="#grab-origin-in-singapore" id="toc-grab-origin-in-singapore" class="nav-link" data-scroll-target="#grab-origin-in-singapore">3.1.1 Grab origin in Singapore</a></li>
  <li><a href="#grab-destination-in-singapore" id="toc-grab-destination-in-singapore" class="nav-link" data-scroll-target="#grab-destination-in-singapore">3.1.2 Grab destination in Singapore</a></li>
  </ul></li>
  <li><a href="#spatial-analysis" id="toc-spatial-analysis" class="nav-link" data-scroll-target="#spatial-analysis">3.2 Spatial Analysis</a>
  <ul class="collapse">
  <li><a href="#net-outflow-from-northern-singapore" id="toc-net-outflow-from-northern-singapore" class="nav-link" data-scroll-target="#net-outflow-from-northern-singapore">3.2.1 Net outflow from northern Singapore</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#kernel-density-estimation" id="toc-kernel-density-estimation" class="nav-link" data-scroll-target="#kernel-density-estimation">3. Kernel Density Estimation</a>
  <ul class="collapse">
  <li><a href="#computing-kde-with-automatic-bandwidth" id="toc-computing-kde-with-automatic-bandwidth" class="nav-link" data-scroll-target="#computing-kde-with-automatic-bandwidth">3.1 Computing KDE with automatic bandwidth</a>
  <ul class="collapse">
  <li><a href="#computing-kde-with-automatic-bandwidth-and-gaussian-kernel" id="toc-computing-kde-with-automatic-bandwidth-and-gaussian-kernel" class="nav-link" data-scroll-target="#computing-kde-with-automatic-bandwidth-and-gaussian-kernel">3.1.1 Computing KDE with automatic bandwidth and gaussian kernel</a></li>
  <li><a href="#computing-kde-with-automatic-bandwidth-and-various-kernels" id="toc-computing-kde-with-automatic-bandwidth-and-various-kernels" class="nav-link" data-scroll-target="#computing-kde-with-automatic-bandwidth-and-various-kernels">3.1.2 Computing KDE with automatic bandwidth and various kernels</a></li>
  </ul></li>
  <li><a href="#comparing-spatial-point-patterns-using-kde" id="toc-comparing-spatial-point-patterns-using-kde" class="nav-link" data-scroll-target="#comparing-spatial-point-patterns-using-kde">3.2 Comparing Spatial Point Patterns using KDE</a>
  <ul class="collapse">
  <li><a href="#extracting-study-areas" id="toc-extracting-study-areas" class="nav-link" data-scroll-target="#extracting-study-areas">3.2.1 Extracting study areas</a></li>
  <li><a href="#combining-grab-points-and-the-study-areas" id="toc-combining-grab-points-and-the-study-areas" class="nav-link" data-scroll-target="#combining-grab-points-and-the-study-areas">3.2.2 Combining grab points and the study areas</a></li>
  <li><a href="#kde-in-central-areas" id="toc-kde-in-central-areas" class="nav-link" data-scroll-target="#kde-in-central-areas">3.2.3 KDE in central areas</a></li>
  <li><a href="#converting-kde-output-into-raster-format" id="toc-converting-kde-output-into-raster-format" class="nav-link" data-scroll-target="#converting-kde-output-into-raster-format">3.2.4 Converting KDE output into raster format</a></li>
  <li><a href="#displaying-kde-on-open-streetmap-of-singapore" id="toc-displaying-kde-on-open-streetmap-of-singapore" class="nav-link" data-scroll-target="#displaying-kde-on-open-streetmap-of-singapore">3.2.5 Displaying KDE on open streetmap of Singapore</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#network-kernel-density-estimation" id="toc-network-kernel-density-estimation" class="nav-link" data-scroll-target="#network-kernel-density-estimation">4.Network Kernel Density Estimation</a>
  <ul class="collapse">
  <li><a href="#extracting-study-areas-1" id="toc-extracting-study-areas-1" class="nav-link" data-scroll-target="#extracting-study-areas-1">4.1 Extracting study areas</a>
  <ul class="collapse">
  <li><a href="#extracting-the-north" id="toc-extracting-the-north" class="nav-link" data-scroll-target="#extracting-the-north">4.1.1 Extracting the North</a></li>
  <li><a href="#extracting-the-east" id="toc-extracting-the-east" class="nav-link" data-scroll-target="#extracting-the-east">4.1.2 Extracting the East</a></li>
  <li><a href="#extracting-the-downtown-core" id="toc-extracting-the-downtown-core" class="nav-link" data-scroll-target="#extracting-the-downtown-core">4.1.3 Extracting the Downtown core</a></li>
  </ul></li>
  <li><a href="#deriving-the-network-constrained-kde-analysis" id="toc-deriving-the-network-constrained-kde-analysis" class="nav-link" data-scroll-target="#deriving-the-network-constrained-kde-analysis">4.2 Deriving the network constrained KDE Analysis</a>
  <ul class="collapse">
  <li><a href="#deriving-kde-in-the-east" id="toc-deriving-kde-in-the-east" class="nav-link" data-scroll-target="#deriving-kde-in-the-east">4.2.1 Deriving KDE in the East</a></li>
  <li><a href="#deriving-kde-in-the-north" id="toc-deriving-kde-in-the-north" class="nav-link" data-scroll-target="#deriving-kde-in-the-north">4.2.2 Deriving KDE in the North</a></li>
  <li><a href="#deriving-kde-in-the-downtown" id="toc-deriving-kde-in-the-downtown" class="nav-link" data-scroll-target="#deriving-kde-in-the-downtown">4.2.3 Deriving KDE in the Downtown</a></li>
  </ul></li>
  <li><a href="#visualising-nkde" id="toc-visualising-nkde" class="nav-link" data-scroll-target="#visualising-nkde">4.3 Visualising nKDE</a>
  <ul class="collapse">
  <li><a href="#visualising-nkde-for-southerndowntown-of-singapore" id="toc-visualising-nkde-for-southerndowntown-of-singapore" class="nav-link" data-scroll-target="#visualising-nkde-for-southerndowntown-of-singapore">4.3.1 Visualising nKDE for Southern/Downtown of Singapore</a></li>
  <li><a href="#visualising-nkde-for-north-of-singapore" id="toc-visualising-nkde-for-north-of-singapore" class="nav-link" data-scroll-target="#visualising-nkde-for-north-of-singapore">4.3.2 Visualising nKDE for North of Singapore</a></li>
  <li><a href="#visualising-nkde-for-east-of-singapore" id="toc-visualising-nkde-for-east-of-singapore" class="nav-link" data-scroll-target="#visualising-nkde-for-east-of-singapore">4.3.3 Visualising nKDE for East of Singapore</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-home Exercise 1 : Application of Spatial Point Patterns Analysis to discover the geographical distribution of Grab hailing services in Singapore</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 4, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><img src="images/header.png" class="img-fluid"></p>
<p>Hello everyone! In tiny dense Singapore, movement of people is large and fast. Hence, in depth analysis of our movement can provide meaningful and actionable insights on our spatial-temporal behaviour.</p>
<p>In Singapore, we move by utilising a multitude of avenues such as buses, MRTs, LRTs and private hail services. In this exercise, I will be exploring the movement of our people using grab. We will be utilising spatial point analysis methods to discover the geographical and spatio-temporal distribution of Grab hailing service locations in Singaore.</p>
<section id="install-load-packages" class="level1">
<h1>1 Install &amp; Load Packages</h1>
<p>We have to install and load these packages into our R environment so that we can utilise the methods in the packages.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(maptools, tidyverse, </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>sf, raster, spatstat, tmap,lubridate,arrow,sp,spNetwork)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Why do we need these packages?</strong></p>
<p>Let me explain the high level purpose of each package.</p>
<p><em>Tidyverse</em></p>
<p>Imagine you have a bunch of dirty data that you woul have to handle. The Tidyverse package helps you handle the data. It has a bunch of packages within it to help handle data. It can do the following:</p>
<ol type="1">
<li><p>readr - reading and writing data into or out of a spreadsheet</p></li>
<li><p>tidyr - organizing and tidying up your data</p></li>
<li><p>ggplot2 - visualizing your data</p></li>
<li><p>dpylr - mainpulating your data, like doing some basic math to it.</p></li>
</ol>
<p><em>maptools</em></p>
<p>SF package provides us with tools to work with data related to maps and geospatial data. It can</p>
<ol type="1">
<li>Read and write geospatial data from and into files.</li>
<li>Manipulate data - like cut out a specific area on a map</li>
<li>Visualize data</li>
</ol>
<p><em>sf</em></p>
<p>It provides a comprehensive and standardized way to represent and manipulate spatial data.</p>
<ol type="1">
<li>Allows you to represent points, lines and polygons</li>
<li>Allows you to represent data using coordinate reference system, and transform data using that.</li>
</ol>
<p><em>raster</em></p>
<p>It help represent the data in a grid format - where the data is divided into a grid of cells and each cell has its own value. It also supports the modification of those cells.</p>
<p>It is also interoperable with other packages like sf, allowing it to be part of a larger data pipeline.</p>
<p>This package is useful when we want to calculate the density of each gridded area .</p>
<p><em>Spatstat</em></p>
<p>We know from previous exercises that different geographical entities on a map can be represented using a shape. Spatstat allows us to represent geographical entities using a point (x,y).</p>
<p>It also allows us to manipulate them, and conduct statistical analysis on their distribution or pattern along a geographical space.</p>
<p><em>lubridate</em></p>
<p>It allow you to manipulate date time data. It allows you to parse, format and do calculations on date time data.</p>
<p>This is very useful considering the <strong>temporal nature</strong> of our analysis. You will see us doing so in this exercise!</p>
<p><em>arrow</em></p>
<p>It helps us deal with tabular data in a fast, scalable and memory efficient way. This is important considering the large size of our data</p>
<p><em>tmap</em></p>
<p>Shows distribution of a characteristic across a geographic space.</p>
</section>
<section id="data" class="level1">
<h1>2 Data</h1>
<section id="data-download" class="level2">
<h2 class="anchored" data-anchor-id="data-download">2.1 Data Download</h2>
<p>Let us first look at the data we are utilising to conduct this analysis.</p>
<table class="table">
<caption>Overview Off Data Used</caption>
<tbody>
<tr class="odd">
<td>Data Name</td>
<td>Description</td>
<td>Type</td>
<td>Format</td>
<td>Source</td>
</tr>
<tr class="even">
<td>Grab-Posisi</td>
<td>Data on where grab taxis are at a specific time, and at what speed.</td>
<td>Aspatial</td>
<td>.parquet</td>
<td><a href="https://engineering.grab.com/grab-posisi">Source</a></td>
</tr>
<tr class="odd">
<td>Road data set</td>
<td>Data on the roads present in Singapore, Malaysia, Brunei.</td>
<td>Geospatial</td>
<td>ESRI shapefile</td>
<td><a href="https://download.geofabrik.de/asia/malaysia-singapore-brunei.html">Source</a></td>
</tr>
<tr class="even">
<td>Master Plan 2019 Subzone Boundary (No Sea)</td>
<td>This data provides the internal and external boundary in Singapore.</td>
<td>Geospatial</td>
<td>.kml</td>
<td><a href="https://beta.data.gov.sg/collections/1749/view">Source</a></td>
</tr>
</tbody>
</table>
</section>
<section id="data-import" class="level2">
<h2 class="anchored" data-anchor-id="data-import">2.2 Data Import</h2>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">Grab-Posisi</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Road Data Set</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false">Master Plan 2019 Subzone Boundary</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>grab <span class="ot">&lt;-</span> <span class="fu">read_parquet</span>(<span class="st">"../../data/GrabPosisi/part-00000-8bbff892-97d2-4011-9961-703e38972569.c000.snappy.parquet"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>roads <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"../../data"</span>,</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">layer =</span> <span class="st">"gis_osm_roads_free_1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `gis_osm_roads_free_1' from data source 
  `C:\shaysnutss\IS1455-GAA\data' using driver `ESRI Shapefile'
Simple feature collection with 1765176 features and 10 fields
Geometry type: LINESTRING
Dimension:     XY
Bounding box:  xmin: 99.66041 ymin: 0.8021131 xmax: 119.2601 ymax: 7.514393
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>mpsz <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"../../data"</span>,</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">layer =</span> <span class="st">"MPSZ-2019"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `MPSZ-2019' from data source `C:\shaysnutss\IS1455-GAA\data' using driver `ESRI Shapefile'
Simple feature collection with 332 features and 6 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 103.6057 ymin: 1.158699 xmax: 104.0885 ymax: 1.470775
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="data-wrangling" class="level2">
<h2 class="anchored" data-anchor-id="data-wrangling">2.3 Data Wrangling</h2>
<p>We now have our data imported into our R environment, means we can interact with it and use it!</p>
<p>However, data often can’t be used as it is . We would have to change the data to fit our analysis needs. And that is what we will be doing in this section!</p>
<p>We will be doing it dataset by dataset:</p>
<section id="master-plan-2019-subzone-boundary-1" class="level3">
<h3 class="anchored" data-anchor-id="master-plan-2019-subzone-boundary-1">2.3.1 Master Plan 2019 Subzone Boundary</h3>
<section id="coordinate-reference-system" class="level4">
<h4 class="anchored" data-anchor-id="coordinate-reference-system">2.3.1.1 Coordinate Reference System</h4>
<p>Let’s start with checking the coordinate reference system of the dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(mpsz)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: WGS 84 
  wkt:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["latitude",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["longitude",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]</code></pre>
</div>
</div>
<p>We know that the coordinate reference system is WGS84. We have to convert it to SVY21. This is because we want to minimise distortions and enable accurate area and distance measurements. The earth is curved, and the WGS84 reference system results in the distance between two points in the equator being different from the distance between the equally spaced points up in north america.</p>
<p>So let’s convert this to SVY21:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>mpsz <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(mpsz, <span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s check if it has been converted correctly</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(mpsz)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Coordinate Reference System:
  User input: EPSG:3414 
  wkt:
PROJCRS["SVY21 / Singapore TM",
    BASEGEOGCRS["SVY21",
        DATUM["SVY21",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4757]],
    CONVERSION["Singapore Transverse Mercator",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",1.36666666666667,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",103.833333333333,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",1,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",28001.642,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",38744.572,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["northing (N)",north,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["easting (E)",east,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Cadastre, engineering survey, topographic mapping."],
        AREA["Singapore - onshore and offshore."],
        BBOX[1.13,103.59,1.47,104.07]],
    ID["EPSG",3414]]</code></pre>
</div>
</div>
</section>
<section id="dropping-z-coordinate" class="level4">
<h4 class="anchored" data-anchor-id="dropping-z-coordinate">2.3.1.2 Dropping Z coordinate</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>mpsz <span class="ot">&lt;-</span> <span class="fu">st_zm</span>(mpsz)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="geometry-validity" class="level4">
<h4 class="anchored" data-anchor-id="geometry-validity">2.3.1.3 Geometry Validity</h4>
<p>I know we have dropped the Z coordinate, but we still want to check if the geometries we have are valid or if they have any errors. Some of the errors could be zero-area polygons or unclosed rings. Ensuring the data is valid and correcting it before analysis is crucial for an accurate and comprehensive analysis.</p>
<p>So this is how we check if the geometries are valid:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">which</span>(<span class="fu">st_is_valid</span>(mpsz) <span class="sc">==</span> <span class="cn">FALSE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6</code></pre>
</div>
</div>
<p>Oh no! We have 6 invalid geometries. Thank god we caught it!</p>
<p>Let’s make it right using this function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>mpsz <span class="ot">&lt;-</span> <span class="fu">st_make_valid</span>(mpsz)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">which</span>(<span class="fu">st_is_valid</span>(mpsz) <span class="sc">==</span> <span class="cn">FALSE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
</section>
<section id="missing-values" class="level4">
<h4 class="anchored" data-anchor-id="missing-values">2.3.1.4 Missing values</h4>
<p>We want to check if there are any empty rows. Datasets can be huge and consequently, we could have many empty rows that is just a waste of memory and processing power. Removing them would be useful.</p>
<p>Here’s how we do it:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the filter function to check for empty rows</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>empty_rows <span class="ot">&lt;-</span> mpsz <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter_all</span>(<span class="fu">all_vars</span>(<span class="fu">is.na</span>(.)))</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Check if there are any empty rows</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">nrow</span>(empty_rows) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"There are empty rows in the sf data tibble.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"There are no empty rows in the sf data tibble.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>There are no empty rows in the sf data tibble.</code></pre>
</div>
</div>
<p>We know that there are no empty rows from running this so we do not need to remove anything.</p>
</section>
<section id="mpsz-check-in" class="level4">
<h4 class="anchored" data-anchor-id="mpsz-check-in">2.3.1.5 mpsz check-in</h4>
<p>Let’s now check the properties of mpsz before moving on:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>mpsz</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 332 features and 6 fields
Geometry type: GEOMETRY
Dimension:     XY
Bounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33
Projected CRS: SVY21 / Singapore TM
First 10 features:
                 SUBZONE_N SUBZONE_C       PLN_AREA_N PLN_AREA_C       REGION_N
1              MARINA EAST    MESZ01      MARINA EAST         ME CENTRAL REGION
2         INSTITUTION HILL    RVSZ05     RIVER VALLEY         RV CENTRAL REGION
3           ROBERTSON QUAY    SRSZ01  SINGAPORE RIVER         SR CENTRAL REGION
4  JURONG ISLAND AND BUKOM    WISZ01  WESTERN ISLANDS         WI    WEST REGION
5             FORT CANNING    MUSZ02           MUSEUM         MU CENTRAL REGION
6         MARINA EAST (MP)    MPSZ05    MARINE PARADE         MP CENTRAL REGION
7                   SUDONG    WISZ03  WESTERN ISLANDS         WI    WEST REGION
8                  SEMAKAU    WISZ02  WESTERN ISLANDS         WI    WEST REGION
9           SOUTHERN GROUP    SISZ02 SOUTHERN ISLANDS         SI CENTRAL REGION
10                 SENTOSA    SISZ01 SOUTHERN ISLANDS         SI CENTRAL REGION
   REGION_C                       geometry
1        CR POLYGON ((33222.98 29588.13...
2        CR POLYGON ((28481.45 30886.22...
3        CR POLYGON ((28087.34 30541, 2...
4        WR MULTIPOLYGON (((13919 22120...
5        CR POLYGON ((29542.53 31041.2,...
6        CR POLYGON ((35279.55 30886.05...
7        WR MULTIPOLYGON (((17759.05 15...
8        WR MULTIPOLYGON (((19713.94 19...
9        CR MULTIPOLYGON (((28298.9 217...
10       CR MULTIPOLYGON (((27524.76 24...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(mpsz)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "sf"         "data.frame"</code></pre>
</div>
</div>
<p>We know that mpsz now is a sf tibble data frame with 332 features and 2 fields with SVY21 as its coordinate reference system.</p>
<p>Let’s plot it to see it visually also!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mpsz)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="removal-of-internal-boundaries" class="level4">
<h4 class="anchored" data-anchor-id="removal-of-internal-boundaries">2.3.1.6 Removal of internal boundaries</h4>
<p>In this analysis, we also want just the singapore boundary so that we can see what grab taxis are within Singapore. We might not need all the internal breakup and boundaries and constantly using that might clog up processing power.</p>
<p>However, there might be use cases where we need the mpsz object in sf type. So let’s save it first by assigning it to another variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>mpsz_sf <span class="ot">&lt;-</span> mpsz</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now let’s remove the interal boudaries:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>mpsz <span class="ot">&lt;-</span> mpsz <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_union</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s plot mpsz now to see the external boundary:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mpsz)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Yay! We have got it.</p>
</section>
</section>
<section id="road-data-set-1" class="level3">
<h3 class="anchored" data-anchor-id="road-data-set-1">2.3.2 Road Data Set</h3>
<section id="coordinate-reference-system-1" class="level4">
<h4 class="anchored" data-anchor-id="coordinate-reference-system-1">2.3.2.1 Coordinate Reference System</h4>
<p>Let us check the coordinate reference system.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_geometry</span>(roads)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Geometry set for 1765176 features 
Geometry type: LINESTRING
Dimension:     XY
Bounding box:  xmin: 99.66041 ymin: 0.8021131 xmax: 119.2601 ymax: 7.514393
Geodetic CRS:  WGS 84
First 5 geometries:</code></pre>
</div>
</div>
<p>We can see it is not in EPSG:3414, therefore, we do a transformation to assign it the right code. We have explained why we do this under the mpsz section.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>roads <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(roads, </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="constriction-of-roads-to-singapore" class="level4">
<h4 class="anchored" data-anchor-id="constriction-of-roads-to-singapore">2.3.2.2 Constriction of roads to Singapore</h4>
<p>The data of the roads is related to roads in multiple countries on top of Singapore. Let us constrict it to just to have roads in Singapore as Singapore is our area of study.</p>
<p>Besides, this will reduce the amount of data tremedously and allow the processing to be faster.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>roads_inSG <span class="ot">&lt;-</span> <span class="fu">st_intersection</span>(roads, mpsz)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="validity-of-geometries" class="level4">
<h4 class="anchored" data-anchor-id="validity-of-geometries">2.3.2.3 Validity Of Geometries</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">which</span>(<span class="fu">st_is_valid</span>(roads_inSG) <span class="sc">==</span> <span class="cn">FALSE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>Luckily, all geometries are validity!</p>
</section>
<section id="missing-values-1" class="level4">
<h4 class="anchored" data-anchor-id="missing-values-1">2.3.2.4 Missing Values</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the filter function to check for empty rows</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>empty_rows <span class="ot">&lt;-</span> roads_inSG <span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter_all</span>(<span class="fu">all_vars</span>(<span class="fu">is.na</span>(.)))</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Check if there are any empty rows</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">nrow</span>(empty_rows) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"There are empty rows in the sf data tibble.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"There are no empty rows in the sf data tibble.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>There are no empty rows in the sf data tibble.</code></pre>
</div>
</div>
<p>Luckily, there are no empty values again!</p>
</section>
</section>
<section id="grab-posisi-1" class="level3">
<h3 class="anchored" data-anchor-id="grab-posisi-1">2.3.3 Grab Posisi</h3>
<p>Now let’s wrangle the data of Grab posisi.</p>
<section id="convert-data-type" class="level4">
<h4 class="anchored" data-anchor-id="convert-data-type">2.3.3.1 Convert Data type</h4>
<p>Here we convert the int data type to date time data type. We are not using mutate, as we are over writing the data field in the file.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>grab<span class="sc">$</span>pingtimestamp <span class="ot">&lt;-</span><span class="fu">as_datetime</span>(grab<span class="sc">$</span>pingtimestamp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="origin-datapoints-of-each-ride" class="level4">
<h4 class="anchored" data-anchor-id="origin-datapoints-of-each-ride">2.3.3.2 Origin Datapoints of Each Ride</h4>
<p>In this data, the location and specifics of each car ride is sent to the server every minute. Here, we only want the data for the origin point for each ride. So let’s wrangle the data this way:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co">#origin</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>grabOrigin <span class="ot">&lt;-</span> grab <span class="sc">%&gt;%</span> <span class="co">#use df</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(trj_id) <span class="sc">%&gt;%</span> <span class="co">#group according to trj_id</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(pingtimestamp) <span class="sc">%&gt;%</span> <span class="co">#sort according to timestamp asc (default)</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">row_number</span>()<span class="sc">==</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> <span class="co">#the first coordinate for every trip should be the origin</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">weekday =</span> <span class="fu">wday</span>(pingtimestamp, <span class="at">label=</span><span class="cn">TRUE</span>, <span class="at">abbr=</span><span class="cn">TRUE</span>),</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">start_hr =</span> <span class="fu">factor</span>(<span class="fu">hour</span>(pingtimestamp)),</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">day =</span> <span class="fu">factor</span>(<span class="fu">mday</span>(pingtimestamp)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="code-walkthrough" class="level5">
<h5 class="anchored" data-anchor-id="code-walkthrough">2.3.3.2.1 Code Walkthrough</h5>
<p>Let me explain step by step so you understand this better!</p>
<p><code>grabOrigin &lt;- grab</code></p>
<p>Here we take the data from the grab data and wrangle it and assign it to grabOrigin.</p>
<p><code>group_by(trj_id)</code></p>
<p>When we use group_by, we can group the different data records in the data by one column, in this case, trj_id. Here, each group will have rows with the same trj_id, meaning all of the rows in one group will relate to one trip.</p>
<p><code>arrange(pingtimestamp)</code></p>
<p>Here in each group, we arrange all the rows according to the time stamp in an ascending order. Hence, the first row will be the origin location the grab taxi departs from.</p>
<p><code>filter(row_number()==1)</code></p>
<p>Filter method is used to filter out the rows that match a criteria.</p>
<p>Here, we take the first row only - only the origin location the taxi departs from matters.</p>
<p><code>mutate(weekday = wday(pingtimestamp, label=TRUE, abbr=TRUE)</code></p>
<p>Mutate function can be used to create a new column. In this case, we create a column called weekday. The wday function extracts the weekday values from pingtimestamp. We fill the weekday column with the value generated by the wday function.</p>
<p><code>start_hr = factor(hour(pingtimestamp))</code></p>
<p>Here, we create a column called start_hr. We use a function called hour to extract the hour from the pingtimestamp and then place it into the start_hr column.</p>
<p><code>day = factor(mday(pingtimestamp)))</code></p>
<p>Here, we create a column called day. We use a function called mday to extract the day of the month from the pingtimestamp and then place it into the day column.</p>
<p>I hope the code is clearer now, and you understand how we get the origin data points of each ride.</p>
</section>
</section>
<section id="destination-datapoints-of-each-ride" class="level4">
<h4 class="anchored" data-anchor-id="destination-datapoints-of-each-ride">2.3.3.3 Destination Datapoints of Each Ride</h4>
<p>Let’s do almost the same to get the destination of each trip.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get end</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>destination_df <span class="ot">&lt;-</span> grab <span class="sc">%&gt;%</span> <span class="co">#use df</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(trj_id) <span class="sc">%&gt;%</span> <span class="co">#group according to trj_id</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(pingtimestamp)) <span class="sc">%&gt;%</span> <span class="co">#sort according to timestamp asc (default)</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">row_number</span>()<span class="sc">==</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> <span class="co">#the first coordinate for every trip should be the origin</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">weekday =</span> <span class="fu">wday</span>(pingtimestamp, <span class="at">label=</span><span class="cn">TRUE</span>, <span class="at">abbr=</span><span class="cn">TRUE</span>),</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">end_hr =</span> <span class="fu">factor</span>(<span class="fu">hour</span>(pingtimestamp)),</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">day =</span> <span class="fu">factor</span>(<span class="fu">mday</span>(pingtimestamp)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The code is mostly the same except the arrange(desc()) where we arranged the rows descendingly</p>
</section>
<section id="coordinate-reference-frame" class="level4">
<h4 class="anchored" data-anchor-id="coordinate-reference-frame">2.3.3.4 Coordinate reference frame</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>grabOrigin <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(grabOrigin, <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"rawlng"</span>, <span class="st">"rawlat"</span>), <span class="at">crs =</span> <span class="dv">4326</span>) <span class="sc">%&gt;%</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>destination_df <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(destination_df, <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"rawlng"</span>, <span class="st">"rawlat"</span>), <span class="at">crs =</span> <span class="dv">4326</span>) <span class="sc">%&gt;%</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Again, we transform the coordinate reference system into SVY21.</p>
<p>Let’s check if it’s been transformed correctly.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_geometry</span>(grabOrigin) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Geometry set for 28000 features 
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 3661.475 ymin: 25201.14 xmax: 49845.23 ymax: 49685.08
Projected CRS: SVY21 / Singapore TM
First 5 geometries:</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_geometry</span>(destination_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Geometry set for 28000 features 
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 3638.685 ymin: 25350.05 xmax: 50024.92 ymax: 49469.41
Projected CRS: SVY21 / Singapore TM
First 5 geometries:</code></pre>
</div>
</div>
<p>And both have been transformed well!</p>
</section>
<section id="validity-of-geometries-1" class="level4">
<h4 class="anchored" data-anchor-id="validity-of-geometries-1">2.3.3.5 Validity Of Geometries</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">which</span>(<span class="fu">st_is_valid</span>(grabOrigin) <span class="sc">==</span> <span class="cn">FALSE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">which</span>(<span class="fu">st_is_valid</span>(destination_df) <span class="sc">==</span> <span class="cn">FALSE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p>Luckily all geometries are valid!</p>
</section>
<section id="drop-z-coordinate" class="level4">
<h4 class="anchored" data-anchor-id="drop-z-coordinate">2.3.3.6 Drop Z coordinate</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>grabOrigin <span class="ot">&lt;-</span> <span class="fu">st_zm</span>(grabOrigin)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>destination_df <span class="ot">&lt;-</span> <span class="fu">st_zm</span>(destination_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="create-ppp-objects" class="level4">
<h4 class="anchored" data-anchor-id="create-ppp-objects">2.3.3.7 Create ppp objects</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>grabOriginPPP <span class="ot">&lt;-</span> <span class="fu">as.ppp</span>(grabOrigin)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>destination_dfPP <span class="ot">&lt;-</span> <span class="fu">as.ppp</span>(destination_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(grabOriginPPP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Let’s look at the summary statistics of the newly created ppp object</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(grabOriginPPP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Marked planar point pattern:  28000 points
Average intensity 2.47621e-05 points per square unit

Coordinates are given to 3 decimal places
i.e. rounded to the nearest multiple of 0.001 units

marks are of type 'character'
Summary:
   Length     Class      Mode 
    28000 character character 

Window: rectangle = [3661.47, 49845.23] x [25201.14, 49685.08] units
                    (46180 x 24480 units)
Window area = 1130760000 square units</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(destination_dfPP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Let’s look at the summary statistics of the newly created ppp object</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(destination_dfPP)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Marked planar point pattern:  28000 points
Average intensity 2.502667e-05 points per square unit

Coordinates are given to 3 decimal places
i.e. rounded to the nearest multiple of 0.001 units

marks are of type 'character'
Summary:
   Length     Class      Mode 
    28000 character character 

Window: rectangle = [3638.69, 50024.92] x [25350.05, 49469.41] units
                    (46390 x 24120 units)
Window area = 1118810000 square units</code></pre>
</div>
</div>
</section>
<section id="handling-duplicate-points" class="level4">
<h4 class="anchored" data-anchor-id="handling-duplicate-points">2.3.3.8 Handling duplicate points</h4>
<p>We are looking at a huge area, and having multiple points in one area might make us miss important details.</p>
<p>So let us check if there are duplicate points.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(<span class="fu">duplicated</span>(grabOrigin))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(<span class="fu">duplicated</span>(destination_df))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
</section>
<section id="conversion-to-owin-objects" class="level4">
<h4 class="anchored" data-anchor-id="conversion-to-owin-objects">2.3.3.9 Conversion To Owin Objects</h4>
<p>We do this to define the region we can do spatial point analysis in. Let’s take a refresher - the points are the locations of our grab taxis. So, in this case, we want to define Singapore as the region we execute spatial point analysis in.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>mpsz_owin <span class="ot">&lt;-</span> <span class="fu">as.owin</span>(mpsz)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>grabOriginPPP_SG <span class="ot">&lt;-</span> grabOriginPPP[mpsz_owin]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>destination_dfPPP_SG <span class="ot">&lt;-</span> destination_dfPP[mpsz_owin]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
</section>
<section id="visualization-spatial-pattern-analysis" class="level1">
<h1>3.Visualization &amp; Spatial Pattern Analysis</h1>
<p>Let’s plot some of our data to understand this better!</p>
<section id="location-visualizations" class="level2">
<h2 class="anchored" data-anchor-id="location-visualizations">3.1 Location Visualizations</h2>
<p>Here we visualise the origin and destination locations of grab to understand them better!</p>
<section id="grab-origin-in-singapore" class="level3">
<h3 class="anchored" data-anchor-id="grab-origin-in-singapore">3.1.1 Grab origin in Singapore</h3>
<p>We can see where the grabs rides generally start off from in Singapore.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>) </span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_shape</span>(mpsz_sf) <span class="sc">+</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_polygons</span>() <span class="sc">+</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_shape</span>(grabOrigin) <span class="sc">+</span></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_dots</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="grab-destination-in-singapore" class="level3">
<h3 class="anchored" data-anchor-id="grab-destination-in-singapore">3.1.2 Grab destination in Singapore</h3>
<p>Here, we can see where the grab rides generally end in Singapore.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>) </span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_shape</span>(mpsz_sf) <span class="sc">+</span></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_polygons</span>() <span class="sc">+</span></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_shape</span>(destination_df) <span class="sc">+</span></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_dots</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="spatial-analysis" class="level2">
<h2 class="anchored" data-anchor-id="spatial-analysis">3.2 Spatial Analysis</h2>
<section id="net-outflow-from-northern-singapore" class="level3">
<h3 class="anchored" data-anchor-id="net-outflow-from-northern-singapore">3.2.1 Net outflow from northern Singapore</h3>
<section id="method-1-of-analysis" class="level4">
<h4 class="anchored" data-anchor-id="method-1-of-analysis">3.2.1.1 Method 1 of analysis</h4>
<p>Though not conclusive, from staring at the before and after pictures, we can see that there are lesser dots in the extreme east in the destination map than the origin map.</p>
<p>Let’s prove this through code!</p>
<p>This was not done much in class and is new, but good for exploration!</p>
<p>Firstly, get’s create a bounding box for the northern part of Singapore to extract the northern part of Singapore as we want to study it.</p>
<p>Let’s extract the north region in Singapore</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>north <span class="ot">&lt;-</span> mpsz_sf <span class="sc">%&gt;%</span> </span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(REGION_N <span class="sc">==</span> <span class="st">"NORTH REGION"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s see what “north” of Singapore looks like:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(north)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(north)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Now let’s see the number of grab cars that are leaving the north:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>carsOriginInNorth <span class="ot">&lt;-</span> <span class="fu">st_intersection</span>(grabOrigin, north)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>carsOriginInNorth <span class="ot">&lt;-</span> <span class="fu">st_intersection</span>(grabOrigin, north)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s get the number now</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>carsOriginInNorth</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 4547 features and 16 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 13681.67 ymin: 35382.98 xmax: 31339.97 ymax: 49685.08
Projected CRS: SVY21 / Singapore TM
# A tibble: 4,547 × 17
   trj_id driving_mode osname pingtimestamp       speed bearing accuracy weekday
 * &lt;chr&gt;  &lt;chr&gt;        &lt;chr&gt;  &lt;dttm&gt;              &lt;dbl&gt;   &lt;int&gt;    &lt;dbl&gt; &lt;ord&gt;  
 1 14555  car          ios    2019-04-10 09:15:04 10.6      107     10   Wed    
 2 79752  car          ios    2019-04-10 10:17:35  7.52      99      6   Wed    
 3 77697  car          ios    2019-04-11 04:44:09  2.12     143     12   Thu    
 4 10587  car          ios    2019-04-11 10:23:59  6.42     101      8   Thu    
 5 45173  car          andro… 2019-04-11 13:08:29 12.0       85      3.9 Thu    
 6 76870  car          ios    2019-04-12 06:19:28  7.31      96      6   Fri    
 7 79546  car          andro… 2019-04-12 07:22:33 17.0       83      3.9 Fri    
 8 66711  car          ios    2019-04-12 08:10:38 18.3       12      8   Fri    
 9 35891  car          ios    2019-04-13 03:35:23  2.71     354      5   Sat    
10 76149  car          andro… 2019-04-13 10:05:54 17.6       86      3.9 Sat    
# ℹ 4,537 more rows
# ℹ 9 more variables: start_hr &lt;fct&gt;, day &lt;fct&gt;, SUBZONE_N &lt;chr&gt;,
#   SUBZONE_C &lt;chr&gt;, PLN_AREA_N &lt;chr&gt;, PLN_AREA_C &lt;chr&gt;, REGION_N &lt;chr&gt;,
#   REGION_C &lt;chr&gt;, geometry &lt;POINT [m]&gt;</code></pre>
</div>
</div>
<p>We can see 4547 cars are leaving the North</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>) </span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_shape</span>(north) <span class="sc">+</span></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_polygons</span>() <span class="sc">+</span></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_shape</span>(carsOriginInNorth) <span class="sc">+</span></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_dots</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-53-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Now, let’s see the number of cars arriving to the north:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>carsDestInNorth <span class="ot">&lt;-</span> <span class="fu">st_intersection</span>(destination_df, north)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s get the number now:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>carsDestInNorth</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 4242 features and 16 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: 13369.5 ymin: 35350.07 xmax: 31403.56 ymax: 49469.41
Projected CRS: SVY21 / Singapore TM
# A tibble: 4,242 × 17
   trj_id driving_mode osname pingtimestamp       speed bearing accuracy weekday
 * &lt;chr&gt;  &lt;chr&gt;        &lt;chr&gt;  &lt;dttm&gt;              &lt;dbl&gt;   &lt;int&gt;    &lt;dbl&gt; &lt;ord&gt;  
 1 69056  car          andro… 2019-04-21 05:02:36 13.2      348      3.9 Sun    
 2 49387  car          ios    2019-04-21 04:21:53  4.07     283      8   Sun    
 3 47116  car          ios    2019-04-20 10:42:37 14.4      280     10   Sat    
 4 68012  car          andro… 2019-04-20 08:27:09 14.2      266      5   Sat    
 5 10894  car          andro… 2019-04-18 11:50:43  0          0      3   Thu    
 6 74071  car          andro… 2019-04-18 10:58:28 15.7      348      3.9 Thu    
 7 9325   car          ios    2019-04-15 02:47:36  7.37     349      5   Mon    
 8 80203  car          andro… 2019-04-11 18:29:44 17.3        3      4   Thu    
 9 76951  car          ios    2019-04-21 23:47:07 10.3       26      6   Sun    
10 19847  car          andro… 2019-04-21 23:40:18  8.20      26     11   Sun    
# ℹ 4,232 more rows
# ℹ 9 more variables: end_hr &lt;fct&gt;, day &lt;fct&gt;, SUBZONE_N &lt;chr&gt;,
#   SUBZONE_C &lt;chr&gt;, PLN_AREA_N &lt;chr&gt;, PLN_AREA_C &lt;chr&gt;, REGION_N &lt;chr&gt;,
#   REGION_C &lt;chr&gt;, geometry &lt;POINT [m]&gt;</code></pre>
</div>
</div>
<p>We can see that 4242 cars are leaving the North</p>
<p>Let’s see visually how it looks like:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>) </span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_shape</span>(north) <span class="sc">+</span></span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_polygons</span>() <span class="sc">+</span></span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_shape</span>(carsDestInNorth) <span class="sc">+</span></span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tm_dots</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-56-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Though it may not be clear visually, we can see that more cars are leaving the North (4547) than they are going to the North (4242). That makes sense as the North is largely a residential area, and people generally live there more than work there. However, we notice that the difference isn’t too great, and that could be attributed to the fact that the north has slowly been developing many industrial estates that people might work at.</p>
<p>One issue with the data above is that there is a huge portion of area that is Considered “North” is not actually a region considered to be the north.</p>
<p>Refer to the picture below:</p>
<p><img src="images/clipboard-1643911442.png" class="img-fluid"></p>
<p>This area is the central catchment area, with parks and large bodies of water. When thinking of “North Of Singapore”, people generally do not consider the central catchment area as such. And nor is it a place people generally work and live at.</p>
<p>So let’s do a second round of analysis and remove it.</p>
</section>
<section id="method-2-of-analysis" class="level4">
<h4 class="anchored" data-anchor-id="method-2-of-analysis">3.2.1.2 Method 2 of analysis</h4>
<p>For this part, I have used this data : Master Plan 2019 Subzone Boundary (No Sea) from Data.gov.sg. I have not shown the import of wrangling of this data on this page, due to the lack of memory and processing space. However, you can wrangle this data the same way I have wrangled the current mpsz data!</p>
<p>Firstly, get’s create a bounding box for the northern part of Singapore to extract the northern part of Singapore as we want to study it.</p>
<p>These coordinates are not random. I have found them on google maps by selecting points and some trial and error to correctly extract the northern area.</p>
<p><img src="images/code1.PNG" class="img-fluid"></p>
<p>Now, let’s convert the coordinate reference system of the bounding box to match that of mpsz_sf which is SVY21. After that, we will crop Singapore to just the area specified by the bounding box.</p>
<p><img src="images/clipboard-4275436146.png" class="img-fluid"></p>
<p><img src="images/clipboard-3300950019.png" class="img-fluid"></p>
<p>And we have!</p>
<p>Now, let’s see the intersection of grab locations when leaving the northern Singapore.</p>
<p><img src="images/clipboard-3967829211.png" class="img-fluid"></p>
<p><img src="images/clipboard-3197966196.png" class="img-fluid"></p>
<p>Here we can see that our hypothesis is indeed correct. The number of cars starting at north was 3681 while the number of cars arriving at the north was 2838. The gap between the people leaving the North to coming to the north is much greater when i reduced the study area to areas actually relevent to peoplei n the north.</p>
<p>This aligns with common knowledge that the northern parts of Singapore are more residential, and in the mornings, people generally tend to leave the northern areas where they live to go to other parts of Singapore where they work.</p>
</section>
</section>
</section>
</section>
<section id="kernel-density-estimation" class="level1">
<h1>3. Kernel Density Estimation</h1>
<p>Let’s now talk about kernel density estimation.</p>
<p><u><strong>What does it mean?</strong></u></p>
<p>In the maps we have seen above, there are many points scattered throughout Singapore. They might be scattered randomly, or clustered together, distributed evenly as shown below:</p>
<p><img src="images/clipboard-1972438709.png" class="img-fluid"></p>
<p>And moreover, different parts of Singapore might have a different distribution of points. For example, the grabs leaving from yishun might be clustered but the grabs leaving the CBD might be uniform/dispersed.</p>
<p>It is important to understand the distribution of grabs in different locations to understand people’s routines and frequented places.</p>
<p>In summary, the KDE provides a value to ascertain how dense with points different locations in a region are</p>
<p><u><strong>How do we calculate kernel density estimation?</strong></u></p>
<p>Let’s think of this using an analogy. Place a hill over each point, with the peak of the hill right above the point. Hence, the base of the hill will cover that point, and its surrounding areas (maybe even other points). With there being multiple points, the bases of the many hills will overlap. The more the overlap, the more points there are, and the denser that area.</p>
<p>Another thing to take note is that there might be multiple hills close to one another, and so, it is important that the difference in KDE between the two hills is not too sharp. If the points are close , or relatively close together, the points should have somewhat of a similar KDE value. Hence, how we smoothen the hill to ensure a gradual change in KDE value is very important.</p>
<p>There are two variables that we can change when calculating the KDE:</p>
<ul>
<li><p>base of the hill / sigma</p>
<ul>
<li>Fixed bandwidth - base of each hill is fixed</li>
</ul></li>
<li><p>how we smoothen the hill/ kernel - base of each hill is different</p></li>
</ul>
<p>As we change these two variables, we would get different results. Let’s try some variations now.</p>
<p>Firstly, let’s try automatic bandwidth.</p>
<section id="computing-kde-with-automatic-bandwidth" class="level2">
<h2 class="anchored" data-anchor-id="computing-kde-with-automatic-bandwidth">3.1 Computing KDE with automatic bandwidth</h2>
<p>We use automatic bandwidths in this section, where the base of each hill is of different size. Automatic bandwidths can be good in areas where points are really clustered to one another. Hence, sublocations with more points can have smaller based hills to detect small nuanced changes in density. This detection might not be possible if all hills had the same sized hill bases, as the tiny differences in density can be missed out.</p>
<section id="computing-kde-with-automatic-bandwidth-and-gaussian-kernel" class="level3">
<h3 class="anchored" data-anchor-id="computing-kde-with-automatic-bandwidth-and-gaussian-kernel">3.1.1 Computing KDE with automatic bandwidth and gaussian kernel</h3>
<p>There are different ways to calculate the automatic bandwidth. Let’s try some of them/</p>
<section id="using-bw.diggle" class="level4">
<h4 class="anchored" data-anchor-id="using-bw.diggle">3.1.1.1 Using bw.diggle()</h4>
<p>Here we calculate the density of grabs that are just leaving their location.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>grabOriginPPP_SG_km <span class="ot">&lt;-</span> <span class="fu">rescale</span>(grabOriginPPP_SG, <span class="dv">1000</span>, <span class="st">"km"</span>)</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>kde_grabOriginSG_bw_gaus <span class="ot">&lt;-</span> <span class="fu">density</span>(grabOriginPPP_SG_km,</span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>                              <span class="at">sigma=</span>bw.diggle,</span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a>                              <span class="at">edge=</span><span class="cn">TRUE</span>,</span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a>                            <span class="at">kernel=</span><span class="st">"gaussian"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_grabOriginSG_bw_gaus)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-58-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here we calculate the density of grabs that are just arriving to their location.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>grabDestinationPPP_SG <span class="ot">&lt;-</span> <span class="fu">rescale</span>(destination_dfPPP_SG, <span class="dv">1000</span>, <span class="st">"km"</span>)</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>kde_grabDestSG_bw_gaus <span class="ot">&lt;-</span> <span class="fu">density</span>(grabDestinationPPP_SG,</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>                              <span class="at">sigma=</span>bw.diggle,</span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>                              <span class="at">edge=</span><span class="cn">TRUE</span>,</span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>                            <span class="at">kernel=</span><span class="st">"gaussian"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_grabDestSG_bw_gaus)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-60-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The southern part of Singapore is more dense with grab cars as their destination, than their origin. This means that more cars come to the southern part of Singapore than they leave, and that makes sense as the CBD is located there, and a lot of workplaces are situated there. Many people would come to the CBD to work daily, leading to the high densities.</p>
</section>
<section id="using-bw.cvl" class="level4">
<h4 class="anchored" data-anchor-id="using-bw.cvl">3.1.1.1 Using bw.CvL()</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bw.CvL</span>(grabOriginPPP_SG)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   sigma 
6801.213 </code></pre>
</div>
</div>
</section>
<section id="using-bw.scott" class="level4">
<h4 class="anchored" data-anchor-id="using-bw.scott">3.1.1.2 Using bw.scott()</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bw.scott</span>(grabOriginPPP_SG) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  sigma.x   sigma.y 
1587.8068  935.0244 </code></pre>
</div>
</div>
</section>
<section id="using-bw.ppl" class="level4">
<h4 class="anchored" data-anchor-id="using-bw.ppl">3.1.1.3 Using bw.ppl()</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bw.ppl</span>(grabOriginPPP_SG)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   sigma 
382.9118 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>kde_grabOriginSG_ppl_gaus <span class="ot">&lt;-</span>  <span class="fu">density</span>(grabOriginPPP_SG_km, <span class="at">sigma=</span>bw.ppl, <span class="at">edge=</span><span class="cn">TRUE</span>, <span class="at">kernel=</span><span class="st">"gaussian"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_grabOriginSG_bw_gaus, <span class="at">main =</span> <span class="st">"bw.diggle"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-65-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_grabOriginSG_ppl_gaus, <span class="at">main =</span> <span class="st">"bw.ppl"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-65-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>We can see that the densities are more clearly marked when using bw.ppl than when using bw.diggle. This is because the bandwidth, or the base of the hill is much smaller. Hence, the nuances and differences in densities can be more easily picked up.</p>
<p>Baddeley et. (2016) suggested the use of the&nbsp;<em>bw.ppl()</em>&nbsp;algorithm because in ther experience it tends to produce the more appropriate values when the pattern consists predominantly of tight clusters.&nbsp;</p>
</section>
</section>
<section id="computing-kde-with-automatic-bandwidth-and-various-kernels" class="level3">
<h3 class="anchored" data-anchor-id="computing-kde-with-automatic-bandwidth-and-various-kernels">3.1.2 Computing KDE with automatic bandwidth and various kernels</h3>
<p>AS mentioned before, when we use various kernels, we are using different methods to smoothen out the hill to ensure that the differences between two hills aren’t too sharp.</p>
<p>The quartic kernel makes a flat disc-shaped hill, only considering points close to each other.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(grabOriginPPP_SG_km, </span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">sigma=</span>bw.ppl, </span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">edge=</span><span class="cn">TRUE</span>, </span>
<span id="cb92-6"><a href="#cb92-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">kernel=</span><span class="st">"epanechnikov"</span>), </span>
<span id="cb92-7"><a href="#cb92-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Epanechnikov"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-66-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The quartic kernel is similar to epanechnikov the but makes wider hills.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(grabOriginPPP_SG_km,</span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">sigma=</span>bw.ppl, </span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">edge=</span><span class="cn">TRUE</span>, </span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">kernel=</span><span class="st">"quartic"</span>), </span>
<span id="cb93-7"><a href="#cb93-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Quartic"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-67-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The Gaussian kernel is smooth and assigns higher weights to nearby points.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(grabOriginPPP_SG_km, </span>
<span id="cb94-6"><a href="#cb94-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">sigma=</span>bw.ppl, </span>
<span id="cb94-7"><a href="#cb94-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">edge=</span><span class="cn">TRUE</span>, </span>
<span id="cb94-8"><a href="#cb94-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">kernel=</span><span class="st">"gaussian"</span>), </span>
<span id="cb94-9"><a href="#cb94-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Gaussian"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-68-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>he Disc kernel treats all points within a certain distance equally, making a simple, flat circle around each point.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(grabOriginPPP_SG_km, </span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">sigma=</span>bw.ppl, </span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">edge=</span><span class="cn">TRUE</span>, </span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">kernel=</span><span class="st">"disc"</span>), </span>
<span id="cb95-6"><a href="#cb95-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Disc"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-69-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="comparing-spatial-point-patterns-using-kde" class="level2">
<h2 class="anchored" data-anchor-id="comparing-spatial-point-patterns-using-kde">3.2 Comparing Spatial Point Patterns using KDE</h2>
<section id="extracting-study-areas" class="level3">
<h3 class="anchored" data-anchor-id="extracting-study-areas">3.2.1 Extracting study areas</h3>
<p>From our analysis before, we could see that the southern part of Singapore was highly populated due to the CBD and numerous other workplaces. However, we could only see a high level picture of it, now, let’s dive a little deeper and see which areas in the southern part of Singapore were more densely populated with grab cars then the others.</p>
<p>By analysing this, we can somewhat deduce which areas have more workplaces than others!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a>downtown_core <span class="ot">&lt;-</span> mpsz_sf <span class="sc">%&gt;%</span> </span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(PLN_AREA_N <span class="sc">==</span> <span class="st">"DOWNTOWN CORE"</span>)</span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>river_valley <span class="ot">&lt;-</span> mpsz_sf <span class="sc">%&gt;%</span> </span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(PLN_AREA_N <span class="sc">==</span> <span class="st">"RIVER VALLEY"</span>)</span>
<span id="cb96-5"><a href="#cb96-5" aria-hidden="true" tabindex="-1"></a>orchard <span class="ot">&lt;-</span> mpsz_sf <span class="sc">%&gt;%</span> </span>
<span id="cb96-6"><a href="#cb96-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(PLN_AREA_N <span class="sc">==</span> <span class="st">"ORCHARD"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(downtown_core), <span class="at">main =</span> <span class="st">"downtown_core"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-71-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(river_valley), <span class="at">main =</span> <span class="st">"river_valley"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-72-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(orchard), <span class="at">main =</span> <span class="st">"orchard"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-73-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="combining-grab-points-and-the-study-areas" class="level3">
<h3 class="anchored" data-anchor-id="combining-grab-points-and-the-study-areas">3.2.2 Combining grab points and the study areas</h3>
<section id="create-owin-object" class="level4">
<h4 class="anchored" data-anchor-id="create-owin-object">3.2.2.1 Create Owin Object</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>downtown_core <span class="ot">&lt;-</span> <span class="fu">as.owin</span>(downtown_core)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>orchard <span class="ot">&lt;-</span> <span class="fu">as.owin</span>(orchard)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a>river_valley <span class="ot">&lt;-</span> <span class="fu">as.owin</span>(river_valley)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="combination" class="level4">
<h4 class="anchored" data-anchor-id="combination">3.2.2.2 Combination</h4>
<p>Here , we are deriving the points that would be located in each of the locations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>grabDestinationPPP_downtown <span class="ot">&lt;-</span> destination_dfPP[downtown_core]</span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a>grabDestinationPPP_orchard <span class="ot">&lt;-</span> destination_dfPP[orchard]</span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a>grabDestinationPPP_river <span class="ot">&lt;-</span> destination_dfPP[river_valley]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s rescale it, as the default was in meters.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>grabDestinationPPP_downtown <span class="ot">=</span> <span class="fu">rescale</span>(grabDestinationPPP_downtown, <span class="dv">1000</span>, <span class="st">"km"</span>)</span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>grabDestinationPPP_orchard <span class="ot">=</span> <span class="fu">rescale</span>(grabDestinationPPP_orchard, <span class="dv">1000</span>, <span class="st">"km"</span>)</span>
<span id="cb104-3"><a href="#cb104-3" aria-hidden="true" tabindex="-1"></a>grabDestinationPPP_river <span class="ot">=</span> <span class="fu">rescale</span>(grabDestinationPPP_river, <span class="dv">1000</span>, <span class="st">"km"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="plot-points" class="level4">
<h4 class="anchored" data-anchor-id="plot-points">3.2.2.3 Plot points</h4>
<p>Here, we just plot the points of grab cars arriving. Later, we will plot the KDE.</p>
<p>Here we plot grab cars arriving in downtown.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(grabDestinationPPP_downtown)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-79-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here we plot grab cars arriving in orchard.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(grabDestinationPPP_orchard)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-80-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here we plot grab cars arriving in river valley.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(grabDestinationPPP_river)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-81-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>When conducting analysis in a more granular way, we get to see two things</p>
<ol type="1">
<li>The differences in grab cars , and by extension workplaces, between different areas in southern Singapore
<ol type="1">
<li>We can see from these images that downtown is the more popular location in all of the southern parts of singapore that we have analysed.</li>
</ol></li>
<li>We see the distribution of grab cars within each area itself, telling us which locations are more popular, or have drop offs.
<ol type="1">
<li>For example, in Orchard, we can see that the borders of Orchard are more popular.</li>
</ol></li>
</ol>
</section>
</section>
<section id="kde-in-central-areas" class="level3">
<h3 class="anchored" data-anchor-id="kde-in-central-areas">3.2.3 KDE in central areas</h3>
<p>Now let’s compute and plot the KDE in different areas in southern Singapore. This can give us a better idea of the distribution of grab car destinations.</p>
<p>Let’s calculate KDE for downtown.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb108-2"><a href="#cb108-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(grabDestinationPPP_downtown, </span>
<span id="cb108-3"><a href="#cb108-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">sigma=</span>bw.diggle, </span>
<span id="cb108-4"><a href="#cb108-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">edge=</span><span class="cn">TRUE</span>, </span>
<span id="cb108-5"><a href="#cb108-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">kernel=</span><span class="st">"gaussian"</span>),</span>
<span id="cb108-6"><a href="#cb108-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Downtown"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-82-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Let’s calculate KDE for orchard.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(grabDestinationPPP_orchard, </span>
<span id="cb109-3"><a href="#cb109-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">sigma=</span>bw.diggle, </span>
<span id="cb109-4"><a href="#cb109-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">edge=</span><span class="cn">TRUE</span>, </span>
<span id="cb109-5"><a href="#cb109-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">kernel=</span><span class="st">"gaussian"</span>),</span>
<span id="cb109-6"><a href="#cb109-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Orchard"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-83-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Let’s calculate KDE for river valley.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(grabDestinationPPP_river, </span>
<span id="cb110-3"><a href="#cb110-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">sigma=</span>bw.diggle, </span>
<span id="cb110-4"><a href="#cb110-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">edge=</span><span class="cn">TRUE</span>, </span>
<span id="cb110-5"><a href="#cb110-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">kernel=</span><span class="st">"gaussian"</span>),</span>
<span id="cb110-6"><a href="#cb110-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"River Valley"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-84-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>#from here</p>
</section>
<section id="converting-kde-output-into-raster-format" class="level3">
<h3 class="anchored" data-anchor-id="converting-kde-output-into-raster-format">3.2.4 Converting KDE output into raster format</h3>
<p>Why do we do this?</p>
<p>This is mainly just for mapping purposes. Conversion into raster format allows us to visualise the KDE in a pixelated format, allowing us to better understand spatial point patterns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a>kde_grabOriginSG_ppl_gaus_conv <span class="ot">&lt;-</span> <span class="fu">as.SpatialGridDataFrame.im</span>(kde_grabOriginSG_ppl_gaus) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">spplot</span>(kde_grabOriginSG_ppl_gaus_conv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-86-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Next, we will convert the gridded kernal density objects into RasterLayer object by using&nbsp;<em>raster()</em>&nbsp;of&nbsp;<strong>raster</strong>&nbsp;package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a>kde_grabOriginSG_ppl_gaus_conv <span class="ot">&lt;-</span> <span class="fu">raster</span>(kde_grabOriginSG_ppl_gaus_conv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s look at the gridded kernel desnity object</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a>kde_grabOriginSG_ppl_gaus_conv</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class      : RasterLayer 
dimensions : 128, 128, 16384  (nrow, ncol, ncell)
resolution : 0.419757, 0.2695907  (x, y)
extent     : 2.667538, 56.39644, 15.74872, 50.25633  (xmin, xmax, ymin, ymax)
crs        : NA 
source     : memory
names      : v 
values     : -8.533748e-14, 845.4849  (min, max)</code></pre>
</div>
</div>
<p>Notice that the CRS is NA so lets’ set it to SVY21. Remember, we convert everything to the same coordinate reference system!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="fu">projection</span>(kde_grabOriginSG_ppl_gaus_conv) <span class="ot">&lt;-</span> <span class="fu">CRS</span>(<span class="st">"+init=EPSG:3414"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="displaying-kde-on-open-streetmap-of-singapore" class="level3">
<h3 class="anchored" data-anchor-id="displaying-kde-on-open-streetmap-of-singapore">3.2.5 Displaying KDE on open streetmap of Singapore</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_basemap</span>(<span class="st">"OpenStreetMap"</span>) <span class="sc">+</span></span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(kde_grabOriginSG_ppl_gaus_conv) <span class="sc">+</span></span>
<span id="cb117-3"><a href="#cb117-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_raster</span>(<span class="st">"v"</span>, <span class="at">palette =</span> <span class="st">"PuRd"</span>, <span class="at">alpha=</span><span class="fl">0.65</span>) <span class="sc">+</span> </span>
<span id="cb117-4"><a href="#cb117-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">legend.position =</span> <span class="fu">c</span>(<span class="st">"right"</span>, <span class="st">"bottom"</span>), </span>
<span id="cb117-5"><a href="#cb117-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">main.title =</span> <span class="st">"Grab's Origin KDE "</span>,</span>
<span id="cb117-6"><a href="#cb117-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">frame =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-90-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From this, we know that the areas we could be more interested in are the East. the sourthern part of Singapore and Northern part of Singapore. We see that the densities are higher there.</p>
</section>
</section>
</section>
<section id="network-kernel-density-estimation" class="level1">
<h1>4.Network Kernel Density Estimation</h1>
<p>Let’s now carry out network kernel density estimation.</p>
<p><u><strong>What does this mean?</strong></u><br>
It is similar to the kernel density estimation that we have done earlier. Except, this time, we take the roads and network of the place into account as well. We not only want to see where the grab origins are the highest, we want to see near which particular roads they might be the highest. This can be very important for spatial planning and understanding human behaviour.</p>
<section id="extracting-study-areas-1" class="level2">
<h2 class="anchored" data-anchor-id="extracting-study-areas-1">4.1 Extracting study areas</h2>
<p>As mentioned before there are only three areas we are concerned with ar the moment. This is also better for processing and memory power and we do not have to load and process the entire roads dataset.</p>
<section id="extracting-the-north" class="level3">
<h3 class="anchored" data-anchor-id="extracting-the-north">4.1.1 Extracting the North</h3>
<section id="extracting-the-north-from-mpsz" class="level4">
<h4 class="anchored" data-anchor-id="extracting-the-north-from-mpsz">4.1.1.1 Extracting the North from mpsz</h4>
<p>Here, we are extracting the north from mpsz. Thankfully we already have it from previous processing. Let’s print it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a>north</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 41 features and 6 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 12386.29 ymin: 35330.11 xmax: 32377.19 ymax: 50256.33
Projected CRS: SVY21 / Singapore TM
First 10 features:
                 SUBZONE_N SUBZONE_C              PLN_AREA_N PLN_AREA_C
1                 PANG SUA    SKSZ04            SUNGEI KADUT         SK
2                   KHATIB    YSSZ08                  YISHUN         YS
3              MANDAI WEST    MDSZ01                  MANDAI         MD
4             YISHUN SOUTH    YSSZ04                  YISHUN         YS
5            LOWER SELETAR    YSSZ05                  YISHUN         YS
6            MANDAI ESTATE    MDSZ03                  MANDAI         MD
7           YISHUN CENTRAL    YSSZ01                  YISHUN         YS
8                GALI BATU    SKSZ03            SUNGEI KADUT         SK
9               SPRINGLEAF    YSSZ06                  YISHUN         YS
10 CENTRAL WATER CATCHMENT    CCSZ01 CENTRAL WATER CATCHMENT         CC
       REGION_N REGION_C                       geometry
1  NORTH REGION       NR POLYGON ((19156.47 44276.42...
2  NORTH REGION       NR POLYGON ((27819.05 44960.39...
3  NORTH REGION       NR POLYGON ((24684.68 44271.39...
4  NORTH REGION       NR POLYGON ((29187.4 44991.3, ...
5  NORTH REGION       NR POLYGON ((30918.91 45252.69...
6  NORTH REGION       NR POLYGON ((27119.56 45071.12...
7  NORTH REGION       NR POLYGON ((28293.43 44966.31...
8  NORTH REGION       NR POLYGON ((21410.16 41655.28...
9  NORTH REGION       NR POLYGON ((27253.37 41646.98...
10 NORTH REGION       NR POLYGON ((25073.29 43675.36...</code></pre>
</div>
</div>
</section>
<section id="extracting-the-roads-in-the-north" class="level4">
<h4 class="anchored" data-anchor-id="extracting-the-roads-in-the-north">4.1.1.2 Extracting the roads in the North</h4>
<p>Now, let’s get the roads in the north.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a>roads_inNorth <span class="ot">&lt;-</span> <span class="fu">st_intersection</span>(roads, north)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="extracting-the-grab-origin-points-in-the-north" class="level4">
<h4 class="anchored" data-anchor-id="extracting-the-grab-origin-points-in-the-north">4.1.1.3 Extracting the grab origin points in the North</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a>grabO_inNorth <span class="ot">&lt;-</span> <span class="fu">st_intersection</span>(grabOrigin, north)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="extracting-the-east" class="level3">
<h3 class="anchored" data-anchor-id="extracting-the-east">4.1.2 Extracting the East</h3>
<section id="extracting-the-east-from-mpsz" class="level4">
<h4 class="anchored" data-anchor-id="extracting-the-east-from-mpsz">4.1.2.1 Extracting the East from mpsz</h4>
<p>Here, we are extracting the east from mpsz.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a>east <span class="ot">&lt;-</span> mpsz_sf <span class="sc">%&gt;%</span> </span>
<span id="cb122-2"><a href="#cb122-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(REGION_N <span class="sc">==</span> <span class="st">"EAST REGION"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="extracting-the-roads-in-the-east" class="level4">
<h4 class="anchored" data-anchor-id="extracting-the-roads-in-the-east">4.1.2.2 Extracting the roads in the East</h4>
<p>Now, let’s get the roads in the east.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a>roads_inEast <span class="ot">&lt;-</span> <span class="fu">st_intersection</span>(roads, east)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="extracting-the-grab-origin-points-in-the-east" class="level4">
<h4 class="anchored" data-anchor-id="extracting-the-grab-origin-points-in-the-east">4.1.2.3 Extracting the grab origin points in the East</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a>grabO_inEast <span class="ot">&lt;-</span> <span class="fu">st_intersection</span>(grabOrigin, east)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="extracting-the-downtown-core" class="level3">
<h3 class="anchored" data-anchor-id="extracting-the-downtown-core">4.1.3 Extracting the Downtown core</h3>
<section id="extracting-the-downtown-core-from-mpsz" class="level4">
<h4 class="anchored" data-anchor-id="extracting-the-downtown-core-from-mpsz">4.1.3.1 Extracting the downtown core from mpsz</h4>
<p>Here, we are extracting the downtown core from mpsz.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a>downtown_core <span class="ot">&lt;-</span> mpsz_sf <span class="sc">%&gt;%</span> </span>
<span id="cb125-2"><a href="#cb125-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(PLN_AREA_N <span class="sc">==</span> <span class="st">"DOWNTOWN CORE"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="extracting-the-roads-in-the-downtown-core" class="level4">
<h4 class="anchored" data-anchor-id="extracting-the-roads-in-the-downtown-core">4.1.3.2 Extracting the roads in the Downtown core</h4>
<p>Now, let’s get the roads in the Downtown core</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb126"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a>roads_inDowntown <span class="ot">&lt;-</span> <span class="fu">st_intersection</span>(roads, downtown_core)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="extracting-the-grab-origin-points-in-the-downtown-core" class="level4">
<h4 class="anchored" data-anchor-id="extracting-the-grab-origin-points-in-the-downtown-core">4.1.3.3 Extracting the grab origin points in the Downtown core</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a>grabO_in_downtown_core <span class="ot">&lt;-</span> <span class="fu">st_intersection</span>(grabOrigin, downtown_core)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="deriving-the-network-constrained-kde-analysis" class="level2">
<h2 class="anchored" data-anchor-id="deriving-the-network-constrained-kde-analysis">4.2 Deriving the network constrained KDE Analysis</h2>
<section id="deriving-kde-in-the-east" class="level3">
<h3 class="anchored" data-anchor-id="deriving-kde-in-the-east">4.2.1 Deriving KDE in the East</h3>
<section id="preparing-the-lixels-objects" class="level4">
<h4 class="anchored" data-anchor-id="preparing-the-lixels-objects">4.2.1.1 Preparing the lixels objects</h4>
<p>This code snippet means that the roads in the east must be cut into segments, with each of them being at 700m in length, and the minimum length a segment can be is 350m.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a>roads_inEast <span class="ot">&lt;-</span> roads_inEast <span class="sc">%&gt;%</span></span>
<span id="cb128-2"><a href="#cb128-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_sf</span>() <span class="sc">%&gt;%</span></span>
<span id="cb128-3"><a href="#cb128-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_cast</span>(<span class="st">"LINESTRING"</span>)</span>
<span id="cb128-4"><a href="#cb128-4" aria-hidden="true" tabindex="-1"></a>lixelsEast <span class="ot">&lt;-</span> <span class="fu">lixelize_lines</span>(roads_inEast, </span>
<span id="cb128-5"><a href="#cb128-5" aria-hidden="true" tabindex="-1"></a>                         <span class="dv">700</span>, </span>
<span id="cb128-6"><a href="#cb128-6" aria-hidden="true" tabindex="-1"></a>                         <span class="at">mindist =</span> <span class="dv">350</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="generating-line-centre-points" class="level4">
<h4 class="anchored" data-anchor-id="generating-line-centre-points">4.2.1.2 <strong>Generating line centre points</strong></h4>
<p>This code is intended to generate the center points of the lixels using the <strong><code>lines_center</code></strong> function. These central points are used for netKDE.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a>samplesEast <span class="ot">&lt;-</span> <span class="fu">lines_center</span>(lixelsEast)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="performing-netkde" class="level4">
<h4 class="anchored" data-anchor-id="performing-netkde">4.2.1.3 <strong>Performing netKDE</strong></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a>densities <span class="ot">&lt;-</span> <span class="fu">nkde</span>(roads_inEast, </span>
<span id="cb130-2"><a href="#cb130-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">events =</span> grabO_inEast,</span>
<span id="cb130-3"><a href="#cb130-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">w =</span> <span class="fu">rep</span>(<span class="dv">1</span>,<span class="fu">nrow</span>(grabO_inEast)),</span>
<span id="cb130-4"><a href="#cb130-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">samples =</span> samplesEast,</span>
<span id="cb130-5"><a href="#cb130-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">kernel_name =</span> <span class="st">"quartic"</span>,</span>
<span id="cb130-6"><a href="#cb130-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">bw =</span> <span class="dv">300</span>, </span>
<span id="cb130-7"><a href="#cb130-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">div=</span> <span class="st">"bw"</span>, </span>
<span id="cb130-8"><a href="#cb130-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">method =</span> <span class="st">"simple"</span>, </span>
<span id="cb130-9"><a href="#cb130-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">digits =</span> <span class="dv">1</span>, </span>
<span id="cb130-10"><a href="#cb130-10" aria-hidden="true" tabindex="-1"></a>                  <span class="at">tol =</span> <span class="dv">1</span>,</span>
<span id="cb130-11"><a href="#cb130-11" aria-hidden="true" tabindex="-1"></a>                  <span class="at">grid_shape =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>), </span>
<span id="cb130-12"><a href="#cb130-12" aria-hidden="true" tabindex="-1"></a>                  <span class="at">max_depth =</span> <span class="dv">8</span>,</span>
<span id="cb130-13"><a href="#cb130-13" aria-hidden="true" tabindex="-1"></a>                  <span class="at">agg =</span> <span class="dv">5</span>, <span class="co">#we aggregate events within a 5m radius (faster calculation)</span></span>
<span id="cb130-14"><a href="#cb130-14" aria-hidden="true" tabindex="-1"></a>                  <span class="at">sparse =</span> <span class="cn">TRUE</span>,</span>
<span id="cb130-15"><a href="#cb130-15" aria-hidden="true" tabindex="-1"></a>                  <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="deriving-kde-in-the-north" class="level3">
<h3 class="anchored" data-anchor-id="deriving-kde-in-the-north">4.2.2 Deriving KDE in the North</h3>
<section id="preparing-the-lixels-objects-1" class="level4">
<h4 class="anchored" data-anchor-id="preparing-the-lixels-objects-1">4.2.2.1 Preparing the lixels objects</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a>roads_inNorth <span class="ot">&lt;-</span> roads_inNorth <span class="sc">%&gt;%</span></span>
<span id="cb131-2"><a href="#cb131-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_sf</span>() <span class="sc">%&gt;%</span></span>
<span id="cb131-3"><a href="#cb131-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_cast</span>(<span class="st">"LINESTRING"</span>)</span>
<span id="cb131-4"><a href="#cb131-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb131-5"><a href="#cb131-5" aria-hidden="true" tabindex="-1"></a>lixelsNorth <span class="ot">&lt;-</span> <span class="fu">lixelize_lines</span>(roads_inNorth, </span>
<span id="cb131-6"><a href="#cb131-6" aria-hidden="true" tabindex="-1"></a>                         <span class="dv">700</span>, </span>
<span id="cb131-7"><a href="#cb131-7" aria-hidden="true" tabindex="-1"></a>                         <span class="at">mindist =</span> <span class="dv">350</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="generating-line-centre-points-1" class="level4">
<h4 class="anchored" data-anchor-id="generating-line-centre-points-1">4.2.2.2 <strong>Generating line centre points</strong></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb132"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a>samplesNorth <span class="ot">&lt;-</span> <span class="fu">lines_center</span>(lixelsNorth)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="performing-netkde-1" class="level4">
<h4 class="anchored" data-anchor-id="performing-netkde-1">4.2.2.3 <strong>Performing netKDE</strong></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a>densitiesNorth <span class="ot">&lt;-</span> <span class="fu">nkde</span>(roads_inNorth, </span>
<span id="cb133-2"><a href="#cb133-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">events =</span> grabO_inNorth,</span>
<span id="cb133-3"><a href="#cb133-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">w =</span> <span class="fu">rep</span>(<span class="dv">1</span>,<span class="fu">nrow</span>(grabO_inNorth)),</span>
<span id="cb133-4"><a href="#cb133-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">samples =</span> samplesNorth,</span>
<span id="cb133-5"><a href="#cb133-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">kernel_name =</span> <span class="st">"quartic"</span>,</span>
<span id="cb133-6"><a href="#cb133-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">bw =</span> <span class="dv">300</span>, </span>
<span id="cb133-7"><a href="#cb133-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">div=</span> <span class="st">"bw"</span>, </span>
<span id="cb133-8"><a href="#cb133-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">method =</span> <span class="st">"simple"</span>, </span>
<span id="cb133-9"><a href="#cb133-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">digits =</span> <span class="dv">1</span>, </span>
<span id="cb133-10"><a href="#cb133-10" aria-hidden="true" tabindex="-1"></a>                  <span class="at">tol =</span> <span class="dv">1</span>,</span>
<span id="cb133-11"><a href="#cb133-11" aria-hidden="true" tabindex="-1"></a>                  <span class="at">grid_shape =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>), </span>
<span id="cb133-12"><a href="#cb133-12" aria-hidden="true" tabindex="-1"></a>                  <span class="at">max_depth =</span> <span class="dv">8</span>,</span>
<span id="cb133-13"><a href="#cb133-13" aria-hidden="true" tabindex="-1"></a>                  <span class="at">agg =</span> <span class="dv">5</span>, <span class="co">#we aggregate events within a 5m radius (faster calculation)</span></span>
<span id="cb133-14"><a href="#cb133-14" aria-hidden="true" tabindex="-1"></a>                  <span class="at">sparse =</span> <span class="cn">TRUE</span>,</span>
<span id="cb133-15"><a href="#cb133-15" aria-hidden="true" tabindex="-1"></a>                  <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="deriving-kde-in-the-downtown" class="level3">
<h3 class="anchored" data-anchor-id="deriving-kde-in-the-downtown">4.2.3 Deriving KDE in the Downtown</h3>
<section id="preparing-the-lixels-objects-2" class="level4">
<h4 class="anchored" data-anchor-id="preparing-the-lixels-objects-2">4.2.2.1 Preparing the lixels objects</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb134"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" aria-hidden="true" tabindex="-1"></a>roads_inDowntown <span class="ot">&lt;-</span> roads_inDowntown <span class="sc">%&gt;%</span></span>
<span id="cb134-2"><a href="#cb134-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_sf</span>() <span class="sc">%&gt;%</span></span>
<span id="cb134-3"><a href="#cb134-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_cast</span>(<span class="st">"LINESTRING"</span>)</span>
<span id="cb134-4"><a href="#cb134-4" aria-hidden="true" tabindex="-1"></a>lixelsDowntown<span class="ot">&lt;-</span> <span class="fu">lixelize_lines</span>(roads_inDowntown, </span>
<span id="cb134-5"><a href="#cb134-5" aria-hidden="true" tabindex="-1"></a>                         <span class="dv">700</span>, </span>
<span id="cb134-6"><a href="#cb134-6" aria-hidden="true" tabindex="-1"></a>                         <span class="at">mindist =</span> <span class="dv">350</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="generating-line-centre-points-2" class="level4">
<h4 class="anchored" data-anchor-id="generating-line-centre-points-2">4.2.2.3 <strong>Generating line centre points</strong></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a>samplesDowntown <span class="ot">&lt;-</span> <span class="fu">lines_center</span>(lixelsDowntown)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="performing-netkde-2" class="level4">
<h4 class="anchored" data-anchor-id="performing-netkde-2">4.2.2.4 <strong>Performing netKDE</strong></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb136"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" aria-hidden="true" tabindex="-1"></a>densitiesDown <span class="ot">&lt;-</span> <span class="fu">nkde</span>(roads_inDowntown, </span>
<span id="cb136-2"><a href="#cb136-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">events =</span> grabO_in_downtown_core,</span>
<span id="cb136-3"><a href="#cb136-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">w =</span> <span class="fu">rep</span>(<span class="dv">1</span>,<span class="fu">nrow</span>(grabO_in_downtown_core)),</span>
<span id="cb136-4"><a href="#cb136-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">samples =</span> samplesDowntown,</span>
<span id="cb136-5"><a href="#cb136-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">kernel_name =</span> <span class="st">"quartic"</span>,</span>
<span id="cb136-6"><a href="#cb136-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">bw =</span> <span class="dv">300</span>, </span>
<span id="cb136-7"><a href="#cb136-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">div=</span> <span class="st">"bw"</span>, </span>
<span id="cb136-8"><a href="#cb136-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">method =</span> <span class="st">"simple"</span>, </span>
<span id="cb136-9"><a href="#cb136-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">digits =</span> <span class="dv">1</span>, </span>
<span id="cb136-10"><a href="#cb136-10" aria-hidden="true" tabindex="-1"></a>                  <span class="at">tol =</span> <span class="dv">1</span>,</span>
<span id="cb136-11"><a href="#cb136-11" aria-hidden="true" tabindex="-1"></a>                  <span class="at">grid_shape =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>), </span>
<span id="cb136-12"><a href="#cb136-12" aria-hidden="true" tabindex="-1"></a>                  <span class="at">max_depth =</span> <span class="dv">8</span>,</span>
<span id="cb136-13"><a href="#cb136-13" aria-hidden="true" tabindex="-1"></a>                  <span class="at">agg =</span> <span class="dv">5</span>, <span class="co">#we aggregate events within a 5m radius (faster calculation)</span></span>
<span id="cb136-14"><a href="#cb136-14" aria-hidden="true" tabindex="-1"></a>                  <span class="at">sparse =</span> <span class="cn">TRUE</span>,</span>
<span id="cb136-15"><a href="#cb136-15" aria-hidden="true" tabindex="-1"></a>                  <span class="at">verbose =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="visualising-nkde" class="level2">
<h2 class="anchored" data-anchor-id="visualising-nkde">4.3 Visualising nKDE</h2>
<section id="visualising-nkde-for-southerndowntown-of-singapore" class="level3">
<h3 class="anchored" data-anchor-id="visualising-nkde-for-southerndowntown-of-singapore">4.3.1 Visualising nKDE for Southern/Downtown of Singapore</h3>
<p>Before we can visualise the NetKDE values, code chunk below will be used to insert the computed density values (i.e.&nbsp;densities) into&nbsp;<em>samples</em>&nbsp;and&nbsp;<em>lixels</em>&nbsp;objects as&nbsp;<em>density</em>&nbsp;field.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb137"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a>samplesDowntown<span class="sc">$</span>density <span class="ot">&lt;-</span> densitiesDown</span>
<span id="cb137-2"><a href="#cb137-2" aria-hidden="true" tabindex="-1"></a>samplesDowntown<span class="sc">$</span>density <span class="ot">&lt;-</span> densitiesDown</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Since svy21 projection system is in meter, the computed density values are very small i.e.&nbsp;0.0000005. The code chunk below is used to resale the density values from number of events per meter to number of events per kilometer.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb138"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb138-1"><a href="#cb138-1" aria-hidden="true" tabindex="-1"></a><span class="co"># rescaling to help the mapping</span></span>
<span id="cb138-2"><a href="#cb138-2" aria-hidden="true" tabindex="-1"></a>samplesDowntown<span class="sc">$</span>density <span class="ot">&lt;-</span> samplesDowntown<span class="sc">$</span>density<span class="sc">*</span><span class="dv">1000</span></span>
<span id="cb138-3"><a href="#cb138-3" aria-hidden="true" tabindex="-1"></a>samplesDowntown<span class="sc">$</span>density <span class="ot">&lt;-</span> samplesDowntown<span class="sc">$</span>density<span class="sc">*</span><span class="dv">1000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb139"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="co">#tmap_mode('plot')   </span></span>
<span id="cb139-2"><a href="#cb139-2" aria-hidden="true" tabindex="-1"></a><span class="co">#tm_shape(lixelsDowntown)+</span></span>
<span id="cb139-3"><a href="#cb139-3" aria-hidden="true" tabindex="-1"></a>  <span class="co">#tm_lines(col="density")+</span></span>
<span id="cb139-4"><a href="#cb139-4" aria-hidden="true" tabindex="-1"></a> <span class="co"># tm_shape(grabO_in_downtown_core)+</span></span>
<span id="cb139-5"><a href="#cb139-5" aria-hidden="true" tabindex="-1"></a>  <span class="co">#tm_dots()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="visualising-nkde-for-north-of-singapore" class="level3">
<h3 class="anchored" data-anchor-id="visualising-nkde-for-north-of-singapore">4.3.2 Visualising nKDE for North of Singapore</h3>
<p>Before we can visualise the NetKDE values, code chunk below will be used to insert the computed density values (i.e.&nbsp;densities) into&nbsp;<em>samples</em>&nbsp;and&nbsp;<em>lixels</em>&nbsp;objects as&nbsp;<em>density</em>&nbsp;field.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb140"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb140-1"><a href="#cb140-1" aria-hidden="true" tabindex="-1"></a>samplesNorth<span class="sc">$</span>density <span class="ot">&lt;-</span> densitiesNorth</span>
<span id="cb140-2"><a href="#cb140-2" aria-hidden="true" tabindex="-1"></a>samplesNorth<span class="sc">$</span>density <span class="ot">&lt;-</span> densitiesNorth</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Since svy21 projection system is in meter, the computed density values are very small i.e.&nbsp;0.0000005. The code chunk below is used to resale the density values from number of events per meter to number of events per kilometer.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb141"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb141-1"><a href="#cb141-1" aria-hidden="true" tabindex="-1"></a><span class="co"># rescaling to help the mapping</span></span>
<span id="cb141-2"><a href="#cb141-2" aria-hidden="true" tabindex="-1"></a>samplesNorth<span class="sc">$</span>density <span class="ot">&lt;-</span> samplesNorth<span class="sc">$</span>density<span class="sc">*</span><span class="dv">1000</span></span>
<span id="cb141-3"><a href="#cb141-3" aria-hidden="true" tabindex="-1"></a>samplesNorth<span class="sc">$</span>density <span class="ot">&lt;-</span> samplesNorth<span class="sc">$</span>density<span class="sc">*</span><span class="dv">1000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb142"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb142-1"><a href="#cb142-1" aria-hidden="true" tabindex="-1"></a><span class="co">#tmap_mode('plot')</span></span>
<span id="cb142-2"><a href="#cb142-2" aria-hidden="true" tabindex="-1"></a><span class="co">#tm_shape(lixelsNorth)+</span></span>
<span id="cb142-3"><a href="#cb142-3" aria-hidden="true" tabindex="-1"></a> <span class="co"># tm_lines(col="density")+</span></span>
<span id="cb142-4"><a href="#cb142-4" aria-hidden="true" tabindex="-1"></a><span class="co">#tm_shape(grabO_inNorth)+</span></span>
<span id="cb142-5"><a href="#cb142-5" aria-hidden="true" tabindex="-1"></a> <span class="co"># tm_dots()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="visualising-nkde-for-east-of-singapore" class="level3">
<h3 class="anchored" data-anchor-id="visualising-nkde-for-east-of-singapore">4.3.3 Visualising nKDE for East of Singapore</h3>
<p>Before we can visualise the NetKDE values, code chunk below will be used to insert the computed density values (i.e.&nbsp;densities) into&nbsp;<em>samples</em>&nbsp;and&nbsp;<em>lixels</em>&nbsp;objects as&nbsp;<em>density</em>&nbsp;field.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb143"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb143-1"><a href="#cb143-1" aria-hidden="true" tabindex="-1"></a>samplesEast<span class="sc">$</span>density <span class="ot">&lt;-</span> densities</span>
<span id="cb143-2"><a href="#cb143-2" aria-hidden="true" tabindex="-1"></a>lixelsEast<span class="sc">$</span>density <span class="ot">&lt;-</span> densities</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Since svy21 projection system is in meter, the computed density values are very small i.e.&nbsp;0.0000005. The code chunk below is used to resale the density values from number of events per meter to number of events per kilometer.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb144"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb144-1"><a href="#cb144-1" aria-hidden="true" tabindex="-1"></a><span class="co"># rescaling to help the mapping</span></span>
<span id="cb144-2"><a href="#cb144-2" aria-hidden="true" tabindex="-1"></a>samplesEast<span class="sc">$</span>density <span class="ot">&lt;-</span> samplesEast<span class="sc">$</span>density<span class="sc">*</span><span class="dv">1000</span></span>
<span id="cb144-3"><a href="#cb144-3" aria-hidden="true" tabindex="-1"></a>lixelsEast<span class="sc">$</span>density <span class="ot">&lt;-</span> lixelsEast<span class="sc">$</span>density<span class="sc">*</span><span class="dv">1000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb145"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb145-1"><a href="#cb145-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">'plot'</span>)</span>
<span id="cb145-2"><a href="#cb145-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(lixelsEast)<span class="sc">+</span></span>
<span id="cb145-3"><a href="#cb145-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_lines</span>(<span class="at">col=</span><span class="st">"density"</span>)<span class="sc">+</span></span>
<span id="cb145-4"><a href="#cb145-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(grabO_inEast)<span class="sc">+</span></span>
<span id="cb145-5"><a href="#cb145-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Take-Home_Ex01_files/figure-html/unnamed-chunk-117-1.png" class="img-fluid" width="672"></p>
</div>
</div>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>